'use client'

import { Download, FileText, RotateCcw, Trash2, Upload } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { type FormEvent, useState } from 'react'

interface DocumentItem { id: string; title: string; description: string | null; tags: string[]; original_filename: string; content_type: string; file_size: number; expires_on: string | null; created_at: string; deleted_at: string | null; delete_reason: string | null; expiry_reminder_id: string | null; document_categories: { code: string; name: string } | null }
interface Option { id: string; code: string; name: string }
interface EmployeeOption { id: string; employee_number: string; first_name: string; birth_name: string }
interface Options { categories: Option[]; departments: Option[]; roles: Option[]; employees: EmployeeOption[] }
interface Labels { title: string; subtitle: string; upload: string; file: string; documentTitle: string; description: string; tags: string; category: string; visibleToEmployee: string; visibleToRole: string; visibleToDepartment: string; noSelection: string; expiresOn: string; reminderAt: string; reminderForEmployee: string; reminderForRole: string; reminderForDepartment: string; save: string; saving: string; failed: string; empty: string; download: string; delete: string; restore: string; deleteReason: string; deleted: string; expires: string; reminderActive: string; addedOn: string }
const inputClass = 'mt-1 w-full rounded-lg border bg-background px-3 py-2 text-sm'

export function EmployeeDocumentDossier({ employeeId, documents, options, canWrite, canDelete, labels }: { employeeId: string; documents: DocumentItem[]; options: Options | null; canWrite: boolean; canDelete: boolean; labels: Labels }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [failed, setFailed] = useState(false); const [deleteReason, setDeleteReason] = useState('')
  async function upload(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!options) return; setSaving(true); setFailed(false); const form = new FormData(event.currentTarget); const file = form.get('file'); if (!(file instanceof File)) return
    const roleId = String(form.get('roleId') ?? ''); const departmentId = String(form.get('departmentId') ?? ''); const reminderAt = String(form.get('reminderAt') ?? '')
    const audiences = [{ type: 'EMPLOYEE', targetId: employeeId }, ...(roleId ? [{ type: 'MANAGEMENT_ROLE', targetId: roleId }] : []), ...(departmentId ? [{ type: 'DEPARTMENT_BRANCH', targetId: departmentId }] : [])]
    const reminderTargets = [{ type: 'EMPLOYEE', targetId: employeeId }, ...(String(form.get('reminderRoleId') ?? '') ? [{ type: 'MANAGEMENT_ROLE', targetId: String(form.get('reminderRoleId')) }] : []), ...(String(form.get('reminderDepartmentId') ?? '') ? [{ type: 'DEPARTMENT_BRANCH', targetId: String(form.get('reminderDepartmentId')) }] : [])]
    const metadata = { title: form.get('title'), description: form.get('description') || null, tags: String(form.get('tags') ?? '').split(',').map((tag) => tag.trim()).filter(Boolean), categoryId: form.get('categoryId'), expiresOn: form.get('expiresOn') || null, audiences, reminder: reminderAt ? { remindAt: new Date(reminderAt).toISOString(), targets: reminderTargets } : null }
    const body = new FormData(); body.set('file', file); body.set('metadata', JSON.stringify(metadata)); const response = await fetch(`/api/employees/${employeeId}/documents`, { method: 'POST', body }); setSaving(false); setFailed(!response.ok); if (response.ok) { event.currentTarget.reset(); router.refresh() }
  }
  async function mutate(documentId: string, restore: boolean) { setFailed(false); const response = await fetch(`/api/employees/${employeeId}/documents/${documentId}`, { method: restore ? 'PATCH' : 'DELETE', headers: restore ? undefined : { 'content-type': 'application/json' }, body: restore ? undefined : JSON.stringify({ reason: deleteReason }) }); setFailed(!response.ok); if (response.ok) router.refresh() }
  return <section className="mt-8 rounded-2xl border bg-surface p-5 shadow-sm sm:p-6"><header><h2 className="text-xl font-semibold">{labels.title}</h2><p className="mt-1 text-sm text-muted-foreground">{labels.subtitle}</p></header>
    {canWrite && options && <details className="mt-5 rounded-xl border p-4"><summary className="cursor-pointer font-semibold"><span className="inline-flex items-center gap-2"><Upload className="h-4 w-4" />{labels.upload}</span></summary><form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event) => void upload(event)}><label className="text-sm font-medium md:col-span-2">{labels.file}<input accept=".pdf,.png,.jpg,.jpeg,.webp,.docx,.xlsx" className={inputClass} name="file" required type="file" /></label><label className="text-sm font-medium">{labels.documentTitle}<input className={inputClass} name="title" required /></label><label className="text-sm font-medium">{labels.category}<select className={inputClass} name="categoryId" required>{options.categories.map((category) => <option key={category.id} value={category.id}>{category.code} · {category.name}</option>)}</select></label><label className="text-sm font-medium md:col-span-2">{labels.description}<textarea className={inputClass} name="description" rows={2} /></label><label className="text-sm font-medium md:col-span-2">{labels.tags}<input className={inputClass} name="tags" /></label><p className="text-sm font-medium">{labels.visibleToEmployee}</p><span /><label className="text-sm font-medium">{labels.visibleToRole}<select className={inputClass} name="roleId"><option value="">{labels.noSelection}</option>{options.roles.map((role) => <option key={role.id} value={role.id}>{role.code} · {role.name}</option>)}</select></label><label className="text-sm font-medium">{labels.visibleToDepartment}<select className={inputClass} name="departmentId"><option value="">{labels.noSelection}</option>{options.departments.map((department) => <option key={department.id} value={department.id}>{department.code} · {department.name}</option>)}</select></label><label className="text-sm font-medium">{labels.expiresOn}<input className={inputClass} name="expiresOn" type="date" /></label><label className="text-sm font-medium">{labels.reminderAt}<input className={inputClass} name="reminderAt" type="datetime-local" /></label><p className="text-sm font-medium">{labels.reminderForEmployee}</p><span /><label className="text-sm font-medium">{labels.reminderForRole}<select className={inputClass} name="reminderRoleId"><option value="">{labels.noSelection}</option>{options.roles.map((role) => <option key={role.id} value={role.id}>{role.code} · {role.name}</option>)}</select></label><label className="text-sm font-medium">{labels.reminderForDepartment}<select className={inputClass} name="reminderDepartmentId"><option value="">{labels.noSelection}</option>{options.departments.map((department) => <option key={department.id} value={department.id}>{department.code} · {department.name}</option>)}</select></label><button className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground md:col-span-2" disabled={saving}>{saving ? labels.saving : labels.save}</button></form></details>}
    {canDelete && <label className="mt-5 block max-w-xl text-sm font-medium">{labels.deleteReason}<input className={inputClass} value={deleteReason} onChange={(event) => setDeleteReason(event.target.value)} /></label>}{failed && <p className="mt-3 text-sm text-destructive">{labels.failed}</p>}
    <div className="mt-5 grid gap-3 lg:grid-cols-2">{documents.length === 0 ? <p className="text-sm text-muted-foreground">{labels.empty}</p> : documents.map((document) => <article className={`rounded-xl border p-4 ${document.deleted_at ? 'opacity-60' : ''}`} key={document.id}><div className="flex items-start gap-3"><span className="rounded-lg bg-muted p-2"><FileText className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="font-semibold">{document.title}</p><p className="truncate text-xs text-muted-foreground">{document.original_filename} · {Math.ceil(document.file_size / 1024)} KB</p></div>{document.deleted_at && <span className="status-chip">{labels.deleted}</span>}</div>{document.description && <p className="mt-3 text-sm text-muted-foreground">{document.description}</p>}<div className="mt-3 flex flex-wrap gap-1">{document.tags.map((tag) => <span className="status-chip" key={tag}>{tag}</span>)}</div><div className="mt-3 text-xs text-muted-foreground"><p>{labels.addedOn}: {document.created_at.slice(0, 10)}</p>{document.expires_on && <p>{labels.expires}: {document.expires_on}</p>}{document.expiry_reminder_id && <p>{labels.reminderActive}</p>}</div><div className="mt-4 flex flex-wrap gap-2">{!document.deleted_at && <a className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold" href={`/api/employees/${employeeId}/documents/${document.id}/download`}><Download className="h-4 w-4" />{labels.download}</a>}{canDelete && (!document.deleted_at ? <button className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold text-destructive" disabled={!deleteReason.trim()} onClick={() => void mutate(document.id, false)}><Trash2 className="h-4 w-4" />{labels.delete}</button> : <button className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold" onClick={() => void mutate(document.id, true)}><RotateCcw className="h-4 w-4" />{labels.restore}</button>)}</div></article>)}</div>
  </section>
}
