import { redirect } from 'next/navigation'
import { AdminSettingsPageHeader } from '@/components/settings/admin-settings-page-header'
import { TalentRoleExplorer } from '@/components/talent/talent-role-explorer'
import { AuthorizationError, requirePermission } from '@/lib/auth/permissions'
import { getTranslator } from '@/lib/i18n/server'
import { talentRoleExplorerListQuerySchema } from '@/lib/talent/role-explorer-schemas'
import { listTalentRoleExplorerWorkspace } from '@/lib/talent/role-explorer-service'

export default async function TalentRoleExplorerSettingsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  try { await requirePermission('talent:manage') } catch (error) { if (error instanceof AuthorizationError) redirect('/geen-toegang'); throw error }
  const params = await searchParams
  const parsed = talentRoleExplorerListQuerySchema.safeParse({ employeeId: typeof params.employeeId === 'string' ? params.employeeId : undefined, profileVersionId: typeof params.profileVersionId === 'string' ? params.profileVersionId : undefined })
  const [initial, t] = await Promise.all([listTalentRoleExplorerWorkspace('admin', parsed.success ? parsed.data : {}), getTranslator('talent')])
  return <section className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><AdminSettingsPageHeader backHref="/settings/talent" backLabel={t('backToTalent')} title={t('roleExplorerTitle')} subtitle={t('roleExplorerAdminSubtitle')} /><TalentRoleExplorer action="/settings/talent/role-explorer" mode="admin" initial={initial} labels={{ title: t('roleExplorerTitle'), subtitle: t('roleExplorerAdminSubtitle'), employee: t('roleExplorerEmployee'), profile: t('roleExplorerProfile'), chooseEmployee: t('roleExplorerChooseEmployee'), chooseProfile: t('roleExplorerChooseProfile'), compare: t('roleExplorerCompare'), empty: t('roleExplorerEmpty'), chooseTarget: t('roleExplorerChooseTarget'), asOf: t('roleExplorerAsOf'), profileVersion: t('roleExplorerProfileVersion'), profileValidity: t('roleExplorerProfileValidity'), current: t('roleExplorerCurrent'), target: t('roleExplorerTarget'), status: t('roleExplorerStatus'), source: t('roleExplorerSource'), validity: t('roleExplorerValidity'), radarDescription: t('roleExplorerRadarDescription'), radarUnavailable: t('roleExplorerRadarUnavailable'), table: t('roleExplorerTable'), capability: t('roleExplorerCapability'), type: t('roleExplorerType'), reason: t('roleExplorerReason'), nextAction: t('roleExplorerNextAction'), readOnly: t('roleExplorerReadOnly'), scope: t('roleExplorerScope'), noSource: t('roleExplorerNoSource'), noCurrentRecord: t('roleExplorerNoCurrentRecord'), currentProfile: t('roleExplorerCurrentProfile'), noCurrentProfile: t('roleExplorerNoCurrentProfile'), noEmployees: t('roleExplorerNoEmployees'), noProfiles: t('roleExplorerNoProfiles'), noRequirements: t('roleExplorerNoRequirements'), match: t('comparisonMatch'), gap: t('comparisonGap'), missingEvidence: t('comparisonMissingEvidence'), unknown: t('comparisonUnknown'), actionMatch: t('roleExplorerActionMatch'), actionGap: t('roleExplorerActionGap'), actionMissingEvidence: t('roleExplorerActionMissingEvidence'), actionUnknown: t('roleExplorerActionUnknown'), currentJob: t('roleExplorerCurrentJob') }} /></section>
}
