import type { Json } from '@scope/db'
import { NextResponse } from 'next/server'
import { permissionErrorResponse, requirePermission } from '@/lib/auth/permissions'
import { createClient } from '@/lib/supabase/server'
import { fetchPublicHolidays } from './holiday-provider'
import type { HolidayImportInput, HolidayManualInput, HolidayUpdateInput } from './schemas'

export class HolidayError extends Error { constructor(public readonly code: string, public readonly status: number) { super(code); this.name = 'HolidayError' } }
function activeAdministration<T extends { administrationId: string | null }>(context: T): T & { administrationId: string } { if (!context.administrationId) throw new HolidayError('HOLIDAY_ADMINISTRATION_REQUIRED', 400); return context as T & { administrationId: string } }
function databaseError(message: string): never { const code = message.match(/HOLIDAY_[A-Z_]+/)?.[0] ?? 'HOLIDAY_OPERATION_FAILED'; throw new HolidayError(code, code.includes('NOT_FOUND') ? 404 : code.includes('FORBIDDEN') ? 403 : 400) }

export async function previewHolidayImport(input: HolidayImportInput) { await requirePermission('holidays:read'); return fetchPublicHolidays(input.year, input.countryCode) }
export async function listHolidays(year: number) { const auth = activeAdministration(await requirePermission('holidays:read')); const supabase = await createClient(); const { data, error } = await supabase.from('holidays').select('*, holiday_calendars!inner(calendar_year, country_code, imported_at)').eq('administration_id', auth.administrationId).eq('holiday_calendars.calendar_year', year).order('holiday_date').limit(500); if (error) databaseError(error.message); return data ?? [] }
export async function importHolidays(input: HolidayImportInput) { const auth = activeAdministration(await requirePermission('holidays:write')); const holidays = await fetchPublicHolidays(input.year, input.countryCode); const supabase = await createClient(); const snapshot = holidays.map((holiday) => ({ holiday_date: holiday.date, provider_name: holiday.providerName, display_name: holiday.displayName, external_key: holiday.externalKey, holiday_types: holiday.holidayTypes, subdivision_codes: holiday.subdivisionCodes })); const { data, error } = await supabase.rpc('import_holiday_snapshot', { requested_administration_id: auth.administrationId, requested_calendar_year: input.year, requested_country_code: input.countryCode, requested_holidays: snapshot as Json }); if (error || !data) databaseError(error?.message ?? 'HOLIDAY_OPERATION_FAILED'); return { calendarId: data, count: holidays.length } }
export async function createManualHoliday(input: HolidayManualInput) { const auth = activeAdministration(await requirePermission('holidays:write')); const supabase = await createClient(); let calendar = await supabase.from('holiday_calendars').select('id').eq('administration_id', auth.administrationId).eq('calendar_year', input.year).eq('country_code', input.countryCode).maybeSingle(); if (calendar.error) databaseError(calendar.error.message); if (!calendar.data) calendar = await supabase.from('holiday_calendars').insert({ tenant_id: auth.tenantId, administration_id: auth.administrationId, calendar_year: input.year, country_code: input.countryCode }).select('id').single(); if (calendar.error || !calendar.data) databaseError(calendar.error?.message ?? 'HOLIDAY_OPERATION_FAILED'); const result = await supabase.from('holidays').insert({ tenant_id: auth.tenantId, administration_id: auth.administrationId, holiday_calendar_id: calendar.data.id, holiday_date: input.date, provider_name: input.name, display_name: input.name, source: 'MANUAL', created_by: auth.userId, updated_by: auth.userId }).select('id').single(); if (result.error || !result.data) databaseError(result.error?.message ?? 'HOLIDAY_OPERATION_FAILED'); return result.data.id }
export async function updateHoliday(id: string, input: HolidayUpdateInput) { const auth = activeAdministration(await requirePermission('holidays:write')); const supabase = await createClient(); const { error, count } = await supabase.from('holidays').update({ ...(input.isActive !== undefined ? { is_active: input.isActive } : {}), ...(input.displayName ? { display_name: input.displayName } : {}), updated_by: auth.userId }, { count: 'exact' }).eq('id', id).eq('administration_id', auth.administrationId); if (error) databaseError(error.message); if (!count) throw new HolidayError('HOLIDAY_NOT_FOUND', 404) }
export function holidayErrorResponse(error: unknown) { const permission = permissionErrorResponse(error); if (permission) return permission; if (error instanceof HolidayError) return NextResponse.json({ error: error.code }, { status: error.status }); const code = error instanceof Error && error.message.startsWith('HOLIDAY_PROVIDER_') ? error.message : 'HOLIDAY_OPERATION_FAILED'; return NextResponse.json({ error: code }, { status: code.startsWith('HOLIDAY_PROVIDER_') ? 502 : 500 }) }
