import { redirect } from 'next/navigation'
import { LeaveCatalogPage } from '@/components/leave/leave-catalog-page'
import { LeaveEmployeeSetsPanel } from '@/components/leave/leave-employee-sets-panel'
import { LeaveLedgerPanel } from '@/components/leave/leave-ledger-panel'
import { LeaveProfileManagementPanel } from '@/components/leave/leave-profile-management-panel'
import { LeaveSettingsWorkspace } from '@/components/leave/leave-settings-workspace'
import { AdminSettingsPageHeader } from '@/components/settings/admin-settings-page-header'
import { AuthorizationError, requirePermission } from '@/lib/auth/permissions'
import { accrualRuleEditorLabels } from '@/lib/leave/editor-labels'
import { listLeaveCatalog } from '@/lib/leave/leave-service'
import { getTranslator } from '@/lib/i18n/server'

export default async function LeaveAccrualSettingsPage() {
  try { await requirePermission('leave:write') } catch (error) { if (error instanceof AuthorizationError) redirect('/geen-toegang'); throw error }
  const [catalog, pageLabels, settingsLabels] = await Promise.all([listLeaveCatalog(), getTranslator('leave'), getTranslator('settings')])
  const ruleEditor = accrualRuleEditorLabels(pageLabels)
  const ruleSummary = { basis: pageLabels('rule.basis'), amount: pageLabels('rule.amount'), annualFullTimeEntitlement: pageLabels('rule.annualFullTimeEntitlement'), rate: pageLabels('rule.rate'), frequency: pageLabels('rule.frequency'), timing: pageLabels('rule.timing'), expiry: pageLabels('rule.expiry'), validity: pageLabels('rule.validity'), contractHours: pageLabels('type.contractHours'), workedHours: pageLabels('type.workedHours'), payrollPeriod: pageLabels('type.payrollPeriod'), fourWeekly: pageLabels('type.fourWeekly'), monthly: pageLabels('type.monthly'), yearly: pageLabels('type.yearly'), upfront: pageLabels('type.upfront'), arrears: pageLabels('type.arrears'), hoursUnit: pageLabels('rule.hoursUnit'), perHour: pageLabels('rule.perHour'), months: pageLabels('rule.months'), noExpiry: pageLabels('rule.noExpiry'), noValue: pageLabels('rule.noValue'), decimalSeparator: pageLabels('rule.decimalSeparator') }
  const ruleDialog = { addTitle: pageLabels('page.ruleDialog.addTitle'), editTitle: pageLabels('page.ruleDialog.editTitle'), addDescription: pageLabels('page.ruleDialog.addDescription'), editDescription: pageLabels('page.ruleDialog.editDescription'), profileLabel: pageLabels('page.ruleDialog.profileLabel'), profilePlaceholder: pageLabels('page.ruleDialog.profilePlaceholder'), profileHelp: pageLabels('page.ruleDialog.profileHelp'), typeLabel: pageLabels('page.ruleDialog.typeLabel'), typePlaceholder: pageLabels('page.ruleDialog.typePlaceholder'), typeHelp: pageLabels('page.ruleDialog.typeHelp'), noProfiles: pageLabels('page.ruleDialog.noProfiles'), noTypes: pageLabels('page.ruleDialog.noTypes'), alreadyLinked: pageLabels('page.ruleDialog.alreadyLinked'), closeLabel: pageLabels('page.ruleDialog.closeLabel') }
  const catalogLabels = { addType: pageLabels('page.addType'), addWorkHour: pageLabels('page.addWorkHour'), addOvertime: pageLabels('page.addOvertime'), priorityRules: pageLabels('page.priorityRules'), showInactive: pageLabels('page.showInactive'), empty: pageLabels('page.empty'), emptyDescription: pageLabels('page.emptyDescription'), active: pageLabels('page.active'), inactive: pageLabels('page.inactive'), moreActions: pageLabels('page.moreActions'), colorOverview: pageLabels('page.colorOverview'), colorOverviewDescription: pageLabels('page.colorOverviewDescription'), usedBy: pageLabels('page.usedBy'), noColorUsage: pageLabels('page.noColorUsage'), colorUnused: pageLabels('page.colorUnused'), colorOptions: { blue: pageLabels('type.colorBlue'), teal: pageLabels('type.colorTeal'), green: pageLabels('type.colorGreen'), orange: pageLabels('type.colorOrange'), red: pageLabels('type.colorRed'), primary: pageLabels('type.colorPrimary'), success: pageLabels('type.colorSuccess'), warning: pageLabels('type.colorWarning'), destructive: pageLabels('type.colorDestructive'), accent: pageLabels('type.colorAccent'), muted: pageLabels('type.colorMuted'), sidebar: pageLabels('type.colorSidebar') }, tabs: { leave: pageLabels('page.tabs.leave'), overtime: pageLabels('page.tabs.overtime'), workHours: pageLabels('page.tabs.workHours') }, columns: { name: pageLabels('page.columns.name'), accrual: pageLabels('page.columns.accrual'), expiry: pageLabels('page.columns.expiry'), approval: pageLabels('page.columns.approval'), category: pageLabels('page.columns.category'), profiles: pageLabels('page.columns.profiles'), actions: pageLabels('page.columns.actions') }, approvalYes: pageLabels('page.approvalYes'), approvalNo: pageLabels('page.approvalNo'), perYear: pageLabels('page.perYear'), unlimited: pageLabels('page.unlimited'), annualFteCap: pageLabels('type.annualFteCap'), overtime: pageLabels('type.overtimeCap'), noExpiry: pageLabels('page.noExpiry'), yearEnd: pageLabels('page.yearEnd'), monthsAfterYear: pageLabels('page.monthsAfterYear'), notConfigured: pageLabels('page.notConfigured'), contractHours: pageLabels('type.contractHours'), workedHours: pageLabels('type.workedHours'), payrollPeriod: pageLabels('type.payrollPeriod'), fourWeekly: pageLabels('type.fourWeekly'), monthly: pageLabels('type.monthly'), yearly: pageLabels('type.yearly'), accrualMode: pageLabels('type.accrual'), profilesUsing: pageLabels('page.profilesUsing'), noProfileUsage: pageLabels('page.noProfileUsage'), editType: pageLabels('page.editType'), linkToProfile: pageLabels('page.linkToProfile'), ruleDialog, ruleEditor }
  const setLabels = { title: pageLabels('page.employeeSets.title'), description: pageLabels('page.employeeSets.description'), empty: pageLabels('page.employeeSets.empty'), add: pageLabels('page.employeeSets.add'), addMember: pageLabels('page.employeeSets.addMember'), edit: pageLabels('page.employeeSets.edit'), archive: pageLabels('page.employeeSets.archive'), name: pageLabels('page.employeeSets.name'), profile: pageLabels('page.employeeSets.profile'), priority: pageLabels('page.employeeSets.priority'), members: pageLabels('page.employeeSets.members'), active: pageLabels('page.employeeSets.active'), inactive: pageLabels('page.employeeSets.inactive'), search: pageLabels('page.employeeSets.search'), showInactive: pageLabels('page.employeeSets.showInactive'), modalTitle: pageLabels('page.employeeSets.modalTitle'), memberModalTitle: pageLabels('page.employeeSets.memberModalTitle'), employee: pageLabels('page.employeeSets.employee'), validFrom: pageLabels('page.employeeSets.validFrom'), validUntil: pageLabels('page.employeeSets.validUntil'), descriptionField: pageLabels('page.employeeSets.descriptionField'), save: pageLabels('page.employeeSets.save'), cancel: pageLabels('page.employeeSets.cancel'), saving: pageLabels('page.employeeSets.saving'), saved: pageLabels('page.employeeSets.saved'), failed: pageLabels('page.employeeSets.failed'), flowTitle: pageLabels('page.employeeSets.flowTitle'), flowText: pageLabels('page.employeeSets.flowText'), priorityHelp: pageLabels('page.employeeSets.priorityHelp'), memberHelp: pageLabels('page.employeeSets.memberHelp') }
  const profileLabels = { title: pageLabels('page.profiles.title'), description: pageLabels('page.profiles.description'), add: pageLabels('page.profiles.add'), edit: pageLabels('page.profiles.edit'), setDefault: pageLabels('page.profiles.setDefault'), archive: pageLabels('page.profiles.archive'), name: pageLabels('page.profiles.name'), descriptionField: pageLabels('page.profiles.descriptionField'), status: pageLabels('page.profiles.status'), default: pageLabels('page.profiles.default'), rules: pageLabels('page.profiles.rules'), sets: pageLabels('page.profiles.sets'), assignments: pageLabels('page.profiles.assignments'), active: pageLabels('page.profiles.active'), inactive: pageLabels('page.profiles.inactive'), empty: pageLabels('page.profiles.empty'), emptyDescription: pageLabels('page.profiles.emptyDescription'), noDefault: pageLabels('page.profiles.noDefault'), noDefaultAction: pageLabels('page.profiles.noDefaultAction'), formCreate: pageLabels('page.profiles.formCreate'), formEdit: pageLabels('page.profiles.formEdit'), activeLabel: pageLabels('page.profiles.activeLabel'), defaultLabel: pageLabels('page.profiles.defaultLabel'), defaultHelp: pageLabels('page.profiles.defaultHelp'), save: pageLabels('page.profiles.save'), cancel: pageLabels('page.profiles.cancel'), saving: pageLabels('page.profiles.saving'), failed: pageLabels('page.profiles.failed'), defaultConfirmTitle: pageLabels('page.profiles.defaultConfirmTitle'), defaultConfirm: pageLabels('page.profiles.defaultConfirm'), archiveConfirmTitle: pageLabels('page.profiles.archiveConfirmTitle'), archiveConfirm: pageLabels('page.profiles.archiveConfirm'), archiveBlocked: pageLabels('page.profiles.archiveBlocked'), ruleSectionTitle: pageLabels('page.profiles.ruleSectionTitle'), addRule: pageLabels('page.profiles.addRule'), addRuleEmpty: pageLabels('page.profiles.addRuleEmpty'), editRule: pageLabels('page.profiles.editRule'), emptyRules: pageLabels('page.profiles.emptyRules'), explainTitle: pageLabels('page.profiles.explainTitle'), explainDirect: pageLabels('page.profiles.explainDirect'), explainSet: pageLabels('page.profiles.explainSet'), explainDefault: pageLabels('page.profiles.explainDefault'), explainNote: pageLabels('page.profiles.explainNote'), defaultBadge: pageLabels('page.profiles.defaultBadge'), ruleDialog, ruleEditor, ruleSummary }
  return <div className="mx-auto w-full max-w-7xl space-y-8 px-5 py-8 lg:px-10">
    <AdminSettingsPageHeader backLabel={settingsLabels('admin.backToOverview')} backHref="/settings" eyebrow={settingsLabels('admin.eyebrow')} title={pageLabels('page.title')} subtitle={pageLabels('page.subtitle')} />
    <LeaveSettingsWorkspace labels={{ tabs: { types: pageLabels('page.workspace.tabs.types'), profiles: pageLabels('page.workspace.tabs.profiles'), sets: pageLabels('page.workspace.tabs.sets'), yearEnd: pageLabels('page.workspace.tabs.yearEnd') }, tabsAriaLabel: pageLabels('page.workspace.tabsAriaLabel'), intros: { types: pageLabels('page.workspace.typesIntro'), profiles: pageLabels('page.workspace.profilesIntro'), sets: pageLabels('page.workspace.setsIntro'), yearEnd: pageLabels('page.workspace.yearEndIntro') } }} sections={{
      types: <LeaveCatalogPage initial={catalog} labels={catalogLabels} />,
      profiles: <LeaveProfileManagementPanel catalog={catalog} labels={profileLabels} />,
      sets: <LeaveEmployeeSetsPanel catalog={catalog} labels={setLabels} />,
      yearEnd: <LeaveLedgerPanel labels={{ title: pageLabels('page.ledgerTitle'), description: pageLabels('page.ledgerDescription'), yearStatus: pageLabels('page.yearStatus'), yearLocked: pageLabels('page.yearLocked'), yearActive: pageLabels('page.yearActive'), yearFuture: pageLabels('page.yearFuture'), closeYear: pageLabels('page.closeYear'), closeYearConfirm: pageLabels('page.closeYearConfirm'), closeYearDone: pageLabels('page.closeYearDone'), cancel: pageLabels('page.employeeSets.cancel'), empty: pageLabels('page.ledgerEmpty'), failed: pageLabels('page.ledgerFailed'), loading: pageLabels('page.ledgerLoading'), working: pageLabels('page.ledgerWorking') }} />,
    }} />
  </div>
}
