alter table public.personal_dashboard_widgets drop constraint if exists personal_dashboard_widgets_widget_type_check;
alter table public.personal_dashboard_widgets add constraint personal_dashboard_widgets_widget_type_check check (widget_type in (
  'WELCOME', 'MY_REMINDERS', 'ORGANIZATION_OVERVIEW', 'EMPLOYEE_OVERVIEW',
  'MY_PROFILE', 'PROFILE_COMPLETENESS', 'MY_EMERGENCY_CONTACTS', 'EMPLOYEE_DIRECTORY', 'UPCOMING_BIRTHDAYS',
  'HEADCOUNT_BY_DEPARTMENT', 'GENDER_DISTRIBUTION', 'EDUCATION_MIX', 'NATIONALITY_DISTRIBUTION',
  'MY_CONTRACT_DETAILS', 'CONTRACT_TYPE_MIX', 'EXPIRING_CONTRACTS', 'PROBATION_ALERTS', 'UPCOMING_STARTS',
  'CURRENT_MONTH_ENDS', 'AVERAGE_TENURE', 'EMPLOYMENT_STATUS_MIX', 'EMPLOYMENT_CHANGE_TIMELINE',
  'MY_RECENT_DOCUMENTS', 'EXPIRING_DOCUMENTS', 'DOCUMENTS_BY_CATEGORY', 'DOCUMENTS_PER_EMPLOYEE', 'DOCUMENT_REMINDER_STATUS',
  'MY_SALARY_HISTORY', 'AVERAGE_SALARY_BY_DEPARTMENT', 'SALARY_SCALE_OCCUPANCY', 'PAYMENT_TYPE_MIX', 'COST_ALLOCATION_MIX', 'SALARY_CHANGE_TIMELINE',
  'MY_WEEKLY_ROSTER', 'WEEKDAY_HOURS', 'FTE_BY_DEPARTMENT', 'ROSTER_COVERAGE_BY_DEPARTMENT', 'UPCOMING_HOLIDAYS', 'ACTIVE_REMINDERS', 'ORGANIZATION_SUMMARY', 'WORK_PATTERNS_BY_DEPARTMENT'
));
