import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
const sql = readFileSync('supabase/migrations/20260904100000_document_generation_dg1.sql', 'utf8')
describe('DG1 migration contract', () => {
  it('creates immutable scoped snapshot, idempotency, and dossier storage', () => {
    expect(sql).toContain("create type public.document_generation_status as enum ('PREVIEW', 'FINAL')")
    expect(sql).toContain('create table public.document_generation_snapshots')
    expect(sql).toContain('resolved_document_hash')
    expect(sql).toContain('document_generation_idempotency_snapshot_fk')
    expect(sql).toContain('document_generation_dossier_links')
    expect(sql).toContain('document_generation_source_administration_fk')
    expect(sql).toContain('revoke insert, update, delete on public.document_generation_snapshots')
    expect(sql).toContain('alter table public.document_generation_snapshots enable row level security')
    expect(sql).toContain('alter table public.document_generation_dossier_links enable row level security')
    expect(sql).toContain('tenant_hr_group_employee_fk')
    expect(sql).toContain('document_generation_idempotency_snapshot_idx')
    expect(sql).toContain('final_pdf_size bigint')
  })

  it('uses narrow sealed mutation RPCs with explicit service-role access', () => {
    expect(sql).toContain('create or replace function public.create_document_generation_preview')
    expect(sql).toContain('create or replace function public.finalize_document_generation')
    expect(sql).toContain('create or replace function public.ensure_document_generation_dossier')
    expect(sql).toContain('revoke all on function public.finalize_document_generation')
    expect(sql).toContain('grant execute on function public.finalize_document_generation')
    expect(sql).toContain('grant execute on function public.ensure_document_generation_dossier')
    expect(sql).toContain('to service_role')
    expect(sql).toContain('revoke all on function public.create_document_generation_preview(jsonb) from public, anon, authenticated')
    expect(sql).toContain('revoke all on function public.ensure_document_generation_dossier(uuid, uuid) from public, anon, authenticated')
    expect(sql).toContain('drop function if exists public.finalize_document_generation(uuid, uuid, uuid, text, text, text, text)')
    expect(sql).toContain('requested_file_size bigint')
    expect(sql).toContain('revoke all on public.document_generation_idempotency from public, anon, authenticated')
    expect(sql).toContain('set search_path = pg_catalog, public')
    expect(sql).toContain('pg_advisory_xact_lock')
    expect(sql).toContain('on conflict')
  })

  it('seals FINAL state and keeps audit metadata body-free', () => {
    expect(sql).toContain('guard_document_generation_snapshot')
    expect(sql).toContain('DOCUMENT_GENERATION_FINAL_IMMUTABLE')
    expect(sql).toContain('DOCUMENT_GENERATION_FINAL_ARTIFACT_REQUIRED')
    expect(sql).toContain('document_generation_audit')
    expect(sql).toContain("action in ('PREVIEW_CREATED', 'FINALIZED', 'DOSSIER_LINKED')")
    expect(sql).toContain("jsonb_build_object('finalPdfHash'")
    expect(sql).not.toContain("jsonb_build_object('resolvedDocument'")
    expect(sql).toContain("old.status = 'FINAL'")
    expect(sql).toContain("if snapshot_row.status = 'FINAL'")
  })
})
