import { notFound, redirect } from 'next/navigation'
import { LeaveTypeEditor } from '@/components/leave/leave-type-editor'
import { AdminSettingsPageHeader } from '@/components/settings/admin-settings-page-header'
import { AuthorizationError, requirePermission } from '@/lib/auth/permissions'
import { getTranslator } from '@/lib/i18n/server'
import { getOvertimeSettingsPageData, listLeaveCatalog } from '@/lib/leave/leave-service'

export default async function WorkHourTypePage({ params }: { params: Promise<{ workHourTypeId: string }> }) {
  try { await requirePermission('leave:write') } catch (error) { if (error instanceof AuthorizationError) redirect('/geen-toegang'); throw error }
  const [{ workHourTypeId }, catalog, labels] = await Promise.all([params, listLeaveCatalog(), getTranslator('leave')])
  const workHourType = catalog.workHourTypes.find((item) => item.id === workHourTypeId)
  if (!workHourType) notFound()
  const year = new Date().getFullYear()
  const settingsData = workHourType.category !== 'INFORMATIONAL' ? await getOvertimeSettingsPageData(workHourTypeId, workHourType.category === 'OVERTIME' ? 'OVERTIME' : 'WORK') : null
  return <div className="mx-auto w-full max-w-6xl space-y-6 px-5 py-8 lg:px-10"><AdminSettingsPageHeader backLabel={labels('page.back')} backHref="/settings/leave-accrual?tab=overtime" eyebrow={labels('page.title')} title={labels('type.workHourEditTitle', { name: workHourType.name, year })} /><LeaveTypeEditor existing={workHourType} mode="work" labels={typeLabels(labels)} workHourSettings={settingsData ? { initial: settingsData, labels: overtimeLabels(labels), mode: workHourType.category === 'OVERTIME' ? 'OVERTIME' : 'WORK' } : undefined} /></div>
}

function typeLabels(t: Awaited<ReturnType<typeof getTranslator>>) {
  return { save: t('page.save'), archive: t('page.archive'), saving: t('page.saving'), saved: t('page.saved'), failed: t('page.failed'), tabs: { base: t('type.baseTab'), limits: t('type.limitsTab'), advanced: t('type.advancedTab') }, name: t('type.name'), color: t('type.color'), colorOptions: { blue: t('type.colorBlue'), teal: t('type.colorTeal'), green: t('type.colorGreen'), orange: t('type.colorOrange'), red: t('type.colorRed'), primary: t('type.colorPrimary'), success: t('type.colorSuccess'), warning: t('type.colorWarning'), destructive: t('type.colorDestructive'), accent: t('type.colorAccent'), muted: t('type.colorMuted'), sidebar: t('type.colorSidebar') }, scope: t('type.scope'), scopeStatutory: t('type.scopeStatutory'), scopeNonStatutory: t('type.scopeNonStatutory'), scopeAdv: t('type.scopeAdv'), scopeOther: t('type.scopeOther'), category: t('type.category'), regularWork: t('type.regularWork'), overtime: t('type.overtime'), informational: t('type.informational'), activeLabel: t('type.activeLabel'), selfService: t('type.selfService'), entitlement: t('type.entitlement'), accrual: t('type.accrual'), unlimited: t('type.unlimited'), annualCap: t('type.annualCap'), weeklyFactorCap: t('type.weeklyFactorCap'), annualCapValue: t('type.annualCapValue'), weeklyFactor: t('type.weeklyFactor'), workSettings: { title: t('type.workSettingsTitle'), selfService: t('type.selfService'), pinInCalendar: t('type.pinInCalendar') }, ruleTitle: t('type.ruleTitle'), ruleEmpty: t('type.ruleEmpty'), addRule: t('type.addRule'), notApplicable: t('type.notApplicable'), messages: { inputInvalid: t('messages.inputInvalid'), failed: t('messages.notFound') } }
}

function overtimeLabels(t: Awaited<ReturnType<typeof getTranslator>>) {
  return { managerNotification: t('overtime.managerNotification'), selfService: t('type.selfService'), limitForEveryone: t('overtime.limitForEveryone'), unlimited: t('overtime.unlimited'), monthlyHours: t('overtime.monthlyHours'), yearlyHours: t('overtime.yearlyHours'), contractFactor: t('overtime.contractFactor'), limitHours: t('overtime.limitHours'), factor: t('overtime.factor'), save: t('page.save'), saving: t('page.saving'), saved: t('page.saved'), failed: t('page.failed'), exceptions: t('overtime.exceptions'), addException: t('overtime.addException'), exceptionName: t('overtime.exceptionName'), exceptionType: t('overtime.exceptionType'), exceptionSelfService: t('overtime.exceptionSelfService'), allowEntry: t('overtime.allowEntry'), forbidEntry: t('overtime.forbidEntry'), selectionMode: t('overtime.selectionMode'), onePerson: t('overtime.onePerson'), multiplePeople: t('overtime.multiplePeople'), selectPerson: t('overtime.selectPerson'), selectPeople: t('overtime.selectPeople'), search: t('overtime.search'), selectAll: t('overtime.selectAll'), next: t('overtime.next'), cancel: t('overtime.cancel'), create: t('overtime.create'), created: t('overtime.created'), selectedPeople: t('overtime.selectedPeople'), noExceptions: t('overtime.noExceptions'), notAvailable: t('type.notApplicable'), invalid: t('messages.inputInvalid') }
}
