import type { Translator } from '@/lib/i18n/translator'

export function createDocumentStudioLabels(t: Translator) {
  const categoryCodes = ['EMPLOYMENT', 'COMPENSATION', 'ABSENCE_LEAVE', 'PERFORMANCE_DEVELOPMENT', 'ONBOARDING', 'OFFBOARDING', 'POLICY_COMPLIANCE', 'GENERAL'] as const
  const kindCodes = ['DOCUMENT', 'COVER', 'APPENDIX'] as const
  return {
    library: {
      title: t('library.title'), new: t('library.new'), types: t('library.types'), profiles: t('library.profiles'), empty: t('library.empty'),
      name: t('library.name'), kind: t('library.kind'), language: t('library.language'), category: t('library.category'), status: t('library.status'),
      version: t('library.version'), updated: t('library.updated'), draft: t('library.draft'), active: t('library.active'), archived: t('library.archived'), open: t('library.open'),
      categories: Object.fromEntries(categoryCodes.map((code) => [code, t(`categories.${code}`)])),
      kinds: Object.fromEntries(kindCodes.map((code) => [code, t(`kinds.${code}`)])),
    },
    create: {
      title: t('create.title'), templateKey: t('create.templateKey'), name: t('create.name'), description: t('create.description'), kind: t('create.kind'), language: t('create.language'),
      documentType: t('create.documentType'), profile: t('create.profile'), category: t('create.category'), defaultDossier: t('create.defaultDossier'), save: t('create.save'), cancel: t('create.cancel'), failed: t('create.failed'), noOptions: t('create.noOptions'),
      categories: Object.fromEntries(categoryCodes.map((code) => [code, t(`categories.${code}`)])), kinds: Object.fromEntries(kindCodes.map((code) => [code, t(`kinds.${code}`)])),
    },
    editor: {
      title: t('editor.title'), back: t('editor.back'), save: t('editor.save'), saved: t('editor.saved'), activate: t('editor.activate'), archive: t('editor.archive'), discard: t('editor.discard'), revision: t('editor.revision'), dirty: t('editor.dirty'), clean: t('editor.clean'), content: t('editor.content'), metadata: t('editor.metadata'), composition: t('editor.composition'), compositionDocumentOnly: t('editor.compositionDocumentOnly'), compositionSelect: t('editor.compositionSelect'), compositionAdd: t('editor.compositionAdd'), compositionRemove: t('editor.compositionRemove'), compositionMoveUp: t('editor.compositionMoveUp'), compositionMoveDown: t('editor.compositionMoveDown'), compositionEmpty: t('editor.compositionEmpty'), compositionCoverLimit: t('editor.compositionCoverLimit'), compositionNoOptions: t('editor.compositionNoOptions'), compositionCover: t('editor.compositionCover'), compositionAppendix: t('editor.compositionAppendix'), region: t('editor.region'), regionBody: t('editor.regionBody'), regionHeader: t('editor.regionHeader'), regionFooter: t('editor.regionFooter'), validation: t('editor.validation'), valid: t('editor.valid'), invalid: t('editor.invalid'), validate: t('editor.validate'), activationConfirm: t('editor.activationConfirm'), archiveConfirm: t('editor.archiveConfirm'), conflict: t('editor.conflict'), failed: t('editor.failed'), tags: t('editor.tags'), tagSearch: t('editor.tagSearch'), tagEmpty: t('editor.tagEmpty'), tagNoOptions: t('editor.tagNoOptions'), tagSelected: t('editor.tagSelected'), tagSave: t('editor.tagSave'), tagSaved: t('editor.tagSaved'),
      name: t('create.name'), description: t('create.description'), documentType: t('create.documentType'), profile: t('create.profile'), category: t('create.category'), defaultDossier: t('create.defaultDossier'),
      categories: Object.fromEntries(categoryCodes.map((code) => [code, t(`categories.${code}`)])), kinds: Object.fromEntries(kindCodes.map((code) => [code, t(`kinds.${code}`)])),
      toolbar: {
        paragraph: t('toolbar.paragraph'), heading1: t('toolbar.heading1'), heading2: t('toolbar.heading2'), heading3: t('toolbar.heading3'), fontSize: t('toolbar.fontSize'), fontSizeUnit: t('toolbar.fontSizeUnit'), alignLeft: t('toolbar.alignLeft'), alignCenter: t('toolbar.alignCenter'), alignRight: t('toolbar.alignRight'), alignJustify: t('toolbar.alignJustify'), bold: t('toolbar.bold'), italic: t('toolbar.italic'), underline: t('toolbar.underline'), bulletList: t('toolbar.bulletList'), orderedList: t('toolbar.orderedList'), rule: t('toolbar.rule'), pageBreak: t('toolbar.pageBreak'), table: t('toolbar.table'), tableColumns: t('toolbar.tableColumns'), columns: t('toolbar.columns'), columnsRatio: t('toolbar.columnsRatio'), placeholder: t('toolbar.placeholder'), knownPlaceholder: t('toolbar.knownPlaceholder'), temporalPlaceholder: t('toolbar.temporalPlaceholder'), temporalWas: t('toolbar.temporalWas'), temporalIs: t('toolbar.temporalIs'), temporalWordt: t('toolbar.temporalWordt'), freePlaceholder: t('toolbar.freePlaceholder'), freePlaceholderHint: t('toolbar.freePlaceholderHint'), insertPlaceholder: t('toolbar.insertPlaceholder'), asset: t('toolbar.asset'), assetSelect: t('toolbar.assetSelect'), assetUpload: t('toolbar.assetUpload'), assetAlt: t('toolbar.assetAlt'), assetWidth: t('toolbar.assetWidth'), assetAlign: t('toolbar.assetAlign'), assetInsert: t('toolbar.assetInsert'), assetReplace: t('toolbar.assetReplace'), assetRemove: t('toolbar.assetRemove'), assetNoOptions: t('toolbar.assetNoOptions'), assetUploadFailed: t('toolbar.assetUploadFailed'),
      },
    },
    types: { title: t('types.title'), subtitle: t('types.subtitle'), new: t('types.new'), code: t('types.code'), name: t('types.name'), descriptionNl: t('types.descriptionNl'), descriptionEn: t('types.descriptionEn'), retention: t('types.retention'), permanent: t('types.permanent'), years: t('types.years'), status: t('types.status'), active: t('types.active'), inactive: t('types.inactive'), empty: t('types.empty'), save: t('types.save'), cancel: t('types.cancel'), failed: t('types.failed') },
    profiles: { title: t('profiles.title'), subtitle: t('profiles.subtitle'), new: t('profiles.new'), name: t('profiles.name'), administration: t('profiles.administration'), logo: t('profiles.logo'), noLogo: t('profiles.noLogo'), default: t('profiles.default'), status: t('profiles.status'), active: t('profiles.active'), inactive: t('profiles.inactive'), empty: t('profiles.empty'), save: t('profiles.save'), cancel: t('profiles.cancel'), failed: t('profiles.failed') },
  }
}
