import type { getTranslator } from '@/lib/i18n/server'

type Translator = Awaited<ReturnType<typeof getTranslator>>

export function accrualRuleEditorLabels(t: Translator) {
  return {
    chainTitle: t('rule.chainTitle'),
    chainDescription: t('rule.chainDescription'),
    profile: t('rule.profile'),
    predecessor: t('rule.predecessor'),
    successorStart: t('rule.successorStart'),
    basis: t('rule.basis'),
    period: t('rule.period'),
    timing: t('rule.timing'),
    amountPerYear: t('rule.amountPerYear'),
    amountPerHour: t('rule.amountPerHour'),
    hours: t('rule.hours'),
    minutes: t('rule.minutes'),
    seconds: t('rule.seconds'),
    expiry: t('rule.expiry'),
    pause: t('rule.pause'),
    pauseHelp: t('rule.pauseHelp'),
    workHours: t('rule.workHours'),
    contractHours: t('type.contractHours'),
    workedHours: t('type.workedHours'),
    ageSeniority: t('type.ageSeniority'),
    payrollPeriod: t('type.payrollPeriod'),
    yearly: t('type.yearly'),
    upfront: t('type.upfront'),
    arrears: t('type.arrears'),
    noPredecessor: t('rule.noPredecessor'),
    version: t('rule.version'),
    current: t('rule.current'),
    selected: t('rule.selected'),
    successor: t('rule.successor'),
    validFrom: t('rule.successorStart'),
    validUntil: t('rule.validUntil'),
    noValue: t('rule.noValue'),
    specialRulesLater: t('rule.specialRulesLater'),
    summary: t('rule.summary'),
    save: t('rule.add'),
    cancel: t('type.cancel'),
    saving: t('page.saving'),
    failed: t('messages.inputInvalid'),
    saved: t('page.saved'),
    selectAtLeastOne: t('rule.selectAtLeastOne'),
    noWorkHours: t('rule.noWorkHours'),
    noPauseTypes: t('rule.noPauseTypes'),
  }
}
