import type { getTranslator } from '@/lib/i18n/server'

type Translator = Awaited<ReturnType<typeof getTranslator>>

export function accrualRuleEditorLabels(t: Translator) {
  return {
    newTitle: t('rule.newTitle'),
    editTitle: t('rule.editTitle'),
    editing: t('rule.editing'),
    copyValuesFrom: t('rule.copyValuesFrom'),
    startDate: t('rule.startDate'),
    basis: t('rule.basis'),
    contractHours: t('type.contractHours'),
    contractHoursHelp: t('rule.contractHoursHelp'),
    workedHours: t('type.workedHours'),
    workedHoursHelp: t('rule.workedHoursHelp'),
    periodMode: t('rule.periodMode'),
    payrollPeriod: t('type.payrollPeriod'),
    specificPeriod: t('rule.specificPeriod'),
    fourWeekly: t('type.fourWeekly'),
    monthly: t('type.monthly'),
    yearly: t('type.yearly'),
    timing: t('rule.timing'),
    annualFullTimeEntitlement: t('rule.annualFullTimeEntitlement'),
    annualFullTimeEntitlementHelp: t('rule.annualFullTimeEntitlementHelp'),
    calculatedPreview: t('rule.calculatedPreview'),
    calculatedPreviewHelp: t('rule.calculatedPreviewHelp'),
    calculatedYearly: t('rule.calculatedYearly'),
    calculatedMonthly: t('rule.calculatedMonthly'),
    calculatedFourWeekly: t('rule.calculatedFourWeekly'),
    calculatedPayrollPeriod: t('rule.calculatedPayrollPeriod'),
    partialPeriodHelp: t('rule.partialPeriodHelp'),
    partialPeriodMonthly: t('rule.partialPeriodMonthly'),
    partialPeriodFourWeekly: t('rule.partialPeriodFourWeekly'),
    amountPerHour: t('rule.amountPerHour'),
    hours: t('rule.hours'),
    minutes: t('rule.minutes'),
    seconds: t('rule.seconds'),
    expiry: t('rule.expiry'),
    months: t('rule.months'),
    noExpiry: t('rule.noExpiry'),
    pause: t('rule.pause'),
    pauseHelp: t('rule.pauseHelp'),
    workHours: t('rule.workHours'),
    workHoursHelp: t('rule.workHoursHelp'),
    search: t('rule.search'),
    selectedCount: t('rule.selectedCount'),
    noWorkHours: t('rule.noWorkHours'),
    noPauseTypes: t('rule.noPauseTypes'),
    profileRequired: t('rule.profileRequired'),
    decimalSeparator: t('rule.decimalSeparator'),
    hoursUnit: t('rule.hoursUnit'),
    summary: t('rule.summary'),
    summaryBasis: t('rule.summaryBasis'),
    summaryAmount: t('rule.summaryAmount'),
    summaryFrequency: t('rule.summaryFrequency'),
    summaryTiming: t('rule.summaryTiming'),
    summaryExpiry: t('rule.summaryExpiry'),
    summaryPause: t('rule.summaryPause'),
    summaryPauseTypes: t('rule.summaryPauseTypes'),
    save: t('rule.add'),
    cancel: t('type.cancel'),
    saving: t('page.saving'),
    failed: t('messages.inputInvalid'),
    saved: t('page.saved'),
    upfront: t('type.upfront'),
    arrears: t('type.arrears'),
  }
}
