'use client'

import { useActionState, useState } from 'react'
import { LoaderCircle, Plus, Trash2 } from 'lucide-react'
import { onboardTenant, type ControlActionState } from '@/lib/control/actions'
import { getDictionary } from '@/lib/i18n/dictionary'

const initialState: ControlActionState = { code: 'idle' }

export function OnboardingForm() {
  const labels = getDictionary().onboarding
  const [state, action, pending] = useActionState(onboardTenant, initialState)
  const [rows, setRows] = useState([crypto.randomUUID()])
  return <form action={action} className="mt-8 space-y-7">
    <section className="rounded-2xl border border-border bg-panel p-6"><h2 className="text-xl font-bold">{labels.company}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">{labels.name}<input className="mt-2 h-11 w-full rounded-xl border border-border bg-panel-soft px-4 outline-none focus:border-primary" name="name" placeholder={labels.namePlaceholder} required /></label><label className="text-sm font-semibold">{labels.slug}<input className="mt-2 h-11 w-full rounded-xl border border-border bg-panel-soft px-4 outline-none focus:border-primary" name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder={labels.slugPlaceholder} required /></label><label className="text-sm font-semibold sm:col-span-2">{labels.email}<input className="mt-2 h-11 w-full rounded-xl border border-border bg-panel-soft px-4 outline-none focus:border-primary" name="primaryContactEmail" required type="email" /></label></div></section>
    <fieldset className="rounded-2xl border border-border bg-panel p-6"><legend className="px-2 text-xl font-bold">{labels.model}</legend><div className="grid gap-4 md:grid-cols-2"><label className="rounded-2xl border border-border p-5 has-[:checked]:border-primary has-[:checked]:bg-panel-soft"><input className="mr-3" defaultChecked name="administrationMode" type="radio" value="COMBINED" /><strong>{labels.combined}</strong><span className="mt-2 block text-sm leading-6 text-muted-foreground">{labels.combinedHint}</span></label><label className="rounded-2xl border border-border p-5 has-[:checked]:border-primary has-[:checked]:bg-panel-soft"><input className="mr-3" name="administrationMode" type="radio" value="SEPARATE" /><strong>{labels.separate}</strong><span className="mt-2 block text-sm leading-6 text-muted-foreground">{labels.separateHint}</span></label></div></fieldset>
    <section className="rounded-2xl border border-border bg-panel p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold">{labels.administrations}</h2><p className="mt-1 text-sm text-muted-foreground">{labels.administrationsHint}</p></div><button className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-bold" onClick={() => setRows((current) => [...current, crypto.randomUUID()])} type="button"><Plus size={16} />{labels.addAdministration}</button></div><div className="mt-5 space-y-3">{rows.map((row, index) => <div className="grid gap-3 rounded-xl bg-panel-soft p-4 sm:grid-cols-[150px_minmax(0,1fr)_auto]" key={row}><label className="text-xs font-bold text-muted-foreground">{labels.administrationCode}<input className="mt-2 h-10 w-full rounded-lg border border-border bg-panel px-3 text-foreground" defaultValue={index === 0 ? 'HOLDING' : ''} name="administrationCode" required /></label><label className="text-xs font-bold text-muted-foreground">{labels.administrationName}<input className="mt-2 h-10 w-full rounded-lg border border-border bg-panel px-3 text-foreground" name="administrationName" required /></label><button aria-label={labels.remove} className="self-end rounded-lg p-3 text-danger disabled:opacity-30" disabled={rows.length === 1} onClick={() => setRows((current) => current.filter((id) => id !== row))} type="button"><Trash2 size={18} /></button></div>)}</div></section>
    {state.code !== 'idle' ? <p className="rounded-xl bg-danger-soft px-4 py-3 text-sm text-danger" role="alert">{state.code === 'invalid' ? labels.invalid : labels.failed}</p> : null}
    <div className="flex flex-col justify-between gap-5 rounded-2xl bg-primary p-6 text-primary-foreground sm:flex-row sm:items-center"><div><p className="font-bold">{labels.after}</p><p className="mt-1 max-w-2xl text-sm leading-6 text-primary-foreground/65">{labels.afterHint}</p></div><button className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-accent px-5 py-3 font-bold text-primary disabled:opacity-60" disabled={pending} type="submit">{pending ? <LoaderCircle className="animate-spin" size={18} /> : null}{pending ? labels.submitting : labels.submit}</button></div>
  </form>
}
