import Link from 'next/link'
import { Building2, Gauge, LogOut, Plus, ShieldCheck } from 'lucide-react'
import { getDictionary } from '@/lib/i18n/dictionary'
import { buttonClasses } from '@/components/ui/button'

export function Sidebar({ displayName, role }: { displayName: string; role: 'OWNER' | 'OPERATOR' | 'AUDITOR' }) {
  const dictionary = getDictionary()
  return <aside className="flex min-h-20 items-center justify-between gap-5 bg-primary px-4 py-4 text-primary-foreground lg:fixed lg:inset-y-0 lg:left-0 lg:w-64 lg:flex-col lg:items-stretch lg:px-5 lg:py-7">
    <div><Link className="flex items-center gap-3 rounded-[var(--radius-control)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-focus" href="/dashboard"><span className="grid h-10 w-10 place-items-center rounded-[var(--radius-control)] bg-accent text-accent-foreground"><ShieldCheck size={20} /></span><span><strong className="block text-sm">{dictionary.appName}</strong><small className="text-primary-foreground/65">{dictionary.appTagline}</small></span></Link>
      <nav aria-label={dictionary.navigation.overview} className="mt-10 hidden space-y-2 lg:block"><Link className="flex items-center gap-3 rounded-[var(--radius-control)] bg-primary-foreground/10 px-3 py-2.5 text-sm font-medium focus-visible:outline-2 focus-visible:outline-focus" href="/dashboard"><Gauge size={18} />{dictionary.navigation.overview}</Link><Link className="flex items-center gap-3 rounded-[var(--radius-control)] px-3 py-2.5 text-sm text-primary-foreground/75 transition-colors hover:bg-primary-foreground/10 focus-visible:outline-2 focus-visible:outline-focus" href="/dashboard#klanten"><Building2 size={18} />{dictionary.navigation.tenants}</Link>{role !== 'AUDITOR' ? <Link className="flex items-center gap-3 rounded-[var(--radius-control)] px-3 py-2.5 text-sm text-primary-foreground/75 transition-colors hover:bg-primary-foreground/10 focus-visible:outline-2 focus-visible:outline-focus" href="/dashboard/tenants/new"><Plus size={18} />{dictionary.navigation.newTenant}</Link> : null}</nav>
    </div>
    <div className="flex items-center gap-3 lg:w-full lg:border-t lg:border-primary-foreground/15 lg:pt-5"><span className="grid h-9 w-9 place-items-center rounded-full bg-accent font-semibold text-accent-foreground">{displayName.slice(0, 1).toUpperCase()}</span><span className="hidden min-w-0 flex-1 lg:block"><strong className="block truncate text-sm">{displayName}</strong><small className="text-primary-foreground/65">{dictionary.roles[role]}</small></span><Link aria-label={dictionary.navigation.signOut} className={buttonClasses({ variant: 'ghost', size: 'sm', className: 'p-2 text-primary-foreground/70 hover:bg-primary-foreground/10 hover:text-primary-foreground' })} href="/auth/signout"><LogOut size={18} /></Link></div>
  </aside>
}
