import { redirect } from 'next/navigation'
import { AdminSettingsPageHeader } from '@/components/settings/admin-settings-page-header'
import { TalentAssessmentWorkspace } from '@/components/talent/talent-assessment-workspace'
import { AuthorizationError, requirePermission } from '@/lib/auth/permissions'
import { getTranslator } from '@/lib/i18n/server'
import { listTalentAssessmentWorkspace } from '@/lib/talent/assessment-service'

export default async function TalentAssessmentSettingsPage() {
  try { await requirePermission('talent-assessment:manage') } catch (error) { if (error instanceof AuthorizationError) redirect('/geen-toegang'); throw error }
  const [initial, t] = await Promise.all([listTalentAssessmentWorkspace('admin'), getTranslator('talent')])
  const labels = { title: t('assessmentTitle'), subtitle: t('assessmentAdminSubtitle'), cycles: t('assessmentCycles'), noCycles: t('assessmentNoCycles'), selectCycle: t('assessmentSelectCycle'), createCycle: t('assessmentCreateCycle'), code: t('assessmentCode'), name: t('assessmentName'), description: t('assessmentDescription'), opensOn: t('assessmentOpensOn'), closesOn: t('assessmentClosesOn'), itemTitle: t('assessmentItemTitle'), sortOrder: t('assessmentSortOrder'), prompt: t('assessmentPrompt'), maxScore: t('assessmentMaxScore'), create: t('assessmentCreate'), save: t('assessmentSave'), submit: t('assessmentSubmit'), status: t('assessmentStatus'), open: t('assessmentOpen'), close: t('assessmentClose'), archive: t('assessmentArchive'), draft: t('assessmentDraft'), opened: t('assessmentOpened'), closed: t('assessmentClosed'), archived: t('assessmentArchived'), response: t('assessmentResponse'), self: t('assessmentSelf'), manager: t('assessmentManager'), participant: t('assessmentParticipant'), chooseParticipant: t('assessmentChooseParticipant'), answer: t('assessmentAnswer'), privateNote: t('assessmentPrivateNote'), privateNoteHint: t('assessmentPrivateNoteHint'), noItems: t('assessmentNoItems'), noResponses: t('assessmentNoResponses'), responseStatus: t('assessmentResponseStatus'), lock: t('assessmentLock'), finalize: t('assessmentFinalize'), reopen: t('assessmentReopen'), saved: t('assessmentSaved'), failed: t('assessmentFailed'), readOnly: t('assessmentAuditHint'), itemFormTitle: t('assessmentItemFormTitle'), itemCreate: t('assessmentItemCreate'), itemEdit: t('assessmentItemEdit'), itemSaved: t('assessmentItemSaved'), question: t('assessmentQuestion'), required: t('assessmentRequired'), optional: t('assessmentOptional'), noParticipants: t('assessmentNoParticipants'), responseHint: t('assessmentResponseHint'), finalizedReadOnly: t('assessmentFinalizedReadOnly'), confirmTitle: t('assessmentConfirmTitle'), confirmOpen: t('assessmentConfirmOpen'), confirmClose: t('assessmentConfirmClose'), confirmArchive: t('assessmentConfirmArchive'), confirmLock: t('assessmentConfirmLock'), confirmFinalize: t('assessmentConfirmFinalize'), confirmReopen: t('assessmentConfirmReopen'), discardTitle: t('assessmentDiscardTitle'), discardDescription: t('assessmentDiscardDescription'), discard: t('assessmentDiscard'), keepEditing: t('assessmentKeepEditing'), cancel: t('assessmentCancel') }
  return <section className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><AdminSettingsPageHeader backHref="/settings/talent" backLabel={t('backToTalent')} title={t('assessmentTitle')} subtitle={t('assessmentAdminSubtitle')} /><TalentAssessmentWorkspace mode="admin" initial={initial} labels={labels} /></section>
}
