'use client'

import { Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { DropdownSelect } from '@/components/ui/dropdown-select'
import type { EnpsBankQuestionRow, EnpsCategoryRow } from '@/lib/research/database'
import type { EnpsQuestionType } from '@/lib/research/schemas'

interface Labels {
  categories: string; questions: string; newCategory: string; newQuestion: string; editCategory: string; editQuestion: string; categoryName: string; category: string; questionText: string; questionType: string; system: string; custom: string; search: string; allCategories: string; save: string; saving: string; cancel: string; edit: string; delete: string; confirmDelete: string; saved: string; failed: string; empty: string
  typeLabels: Record<EnpsQuestionType, string>
}

type DialogState = { kind: 'category'; id?: string; name: string } | { kind: 'question'; id?: string; categoryId: string; text: string; type: EnpsQuestionType }

export function QuestionBankManager({ categories, questions, labels }: { categories: EnpsCategoryRow[]; questions: EnpsBankQuestionRow[]; labels: Labels }) {
  const router = useRouter()
  const [search, setSearch] = useState('')
  const [categoryId, setCategoryId] = useState('ALL')
  const [dialog, setDialog] = useState<DialogState | null>(null)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState<{ kind: 'success' | 'error'; text: string } | null>(null)
  const categoryById = useMemo(() => new Map(categories.map((category) => [category.id, category])), [categories])
  const visible = useMemo(() => { const query = search.trim().toLocaleLowerCase(); return questions.filter((question) => (categoryId === 'ALL' || question.category_id === categoryId) && (!query || question.question_text.toLocaleLowerCase().includes(query))) }, [categoryId, questions, search])

  async function saveDialog(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!dialog) return
    setSaving(true); setMessage(null)
    const base = dialog.kind === 'category' ? '/api/research/question-bank/categories' : '/api/research/question-bank/questions'
    const id = dialog.id
    const body = dialog.kind === 'category' ? { name: dialog.name } : { categoryId: dialog.categoryId, text: dialog.text, type: dialog.type }
    try { const response = await fetch(id ? `${base}/${id}` : base, { method: id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error('save'); setDialog(null); setMessage({ kind: 'success', text: labels.saved }); router.refresh() } catch { setMessage({ kind: 'error', text: labels.failed }) } finally { setSaving(false) }
  }

  async function remove(kind: 'categories' | 'questions', id: string) {
    if (!window.confirm(labels.confirmDelete)) return
    setSaving(true); setMessage(null)
    try { const response = await fetch(`/api/research/question-bank/${kind}/${id}`, { method: 'DELETE' }); if (!response.ok) throw new Error('delete'); setMessage({ kind: 'success', text: labels.saved }); router.refresh() } catch { setMessage({ kind: 'error', text: labels.failed }) } finally { setSaving(false) }
  }

  const inputClass = 'mt-2 w-full rounded-xl border bg-background px-4 py-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-focus/20'
  return <div>
    <div className="grid gap-6 xl:grid-cols-[19rem_minmax(0,1fr)]">
      <aside className="h-fit rounded-3xl border bg-surface p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">{labels.categories}</h2><button aria-label={labels.newCategory} className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground" onClick={() => setDialog({ kind: 'category', name: '' })} type="button"><Plus aria-hidden="true" size={16} /></button></div><div className="mt-3 space-y-1"><button className={`w-full rounded-xl px-3 py-2.5 text-left text-sm font-medium ${categoryId === 'ALL' ? 'bg-accent text-accent-foreground' : 'hover:bg-muted'}`} onClick={() => setCategoryId('ALL')} type="button">{labels.allCategories}</button>{categories.map((category) => <div className={`group flex items-center gap-1 rounded-xl ${categoryId === category.id ? 'bg-accent text-accent-foreground' : 'hover:bg-muted'}`} key={category.id}><button className="min-w-0 flex-1 px-3 py-2.5 text-left text-sm font-medium" onClick={() => setCategoryId(category.id)} type="button"><span className="block truncate">{category.name}</span><span className="mt-0.5 block text-[10px] uppercase tracking-[0.1em] text-muted-foreground">{category.is_system ? labels.system : labels.custom}</span></button>{!category.is_system ? <><button aria-label={labels.edit} className="grid size-8 place-items-center rounded-lg opacity-70 hover:bg-background" onClick={() => setDialog({ kind: 'category', id: category.id, name: category.name })} type="button"><Pencil aria-hidden="true" size={13} /></button><button aria-label={labels.delete} className="mr-1 grid size-8 place-items-center rounded-lg text-destructive opacity-70 hover:bg-destructive/10" disabled={saving} onClick={() => void remove('categories', category.id)} type="button"><Trash2 aria-hidden="true" size={13} /></button></> : null}</div>)}</div></aside>
      <section><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">{labels.questions}</h2><button className="button-primary" onClick={() => setDialog({ kind: 'question', categoryId: categoryId === 'ALL' ? categories[0]?.id ?? '' : categoryId, text: '', type: 'LIKERT_5' })} type="button"><Plus aria-hidden="true" size={16} />{labels.newQuestion}</button></div><div className="relative mt-4"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={16} /><input aria-label={labels.search} className="w-full rounded-xl border bg-surface py-3 pl-9 pr-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-focus/20" onChange={(event) => setSearch(event.target.value)} placeholder={labels.search} value={search} /></div>{message ? <p className={`mt-4 rounded-2xl border p-4 text-sm font-medium ${message.kind === 'success' ? 'border-primary/20 bg-accent text-accent-foreground' : 'border-destructive/30 bg-destructive/10 text-destructive'}`} role="status">{message.text}</p> : null}<div className="mt-4 space-y-2">{visible.map((question) => <article className="flex items-start gap-4 rounded-2xl border bg-surface p-4 shadow-sm" key={question.id}><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">{categoryById.get(question.category_id)?.name}</span><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">{question.is_system ? labels.system : labels.custom}</span></div><p className="mt-2 text-sm leading-6">{question.question_text}</p><p className="mt-1 text-xs font-medium text-primary">{labels.typeLabels[question.default_type as EnpsQuestionType]}</p></div>{!question.is_system ? <div className="flex shrink-0 gap-1"><button aria-label={labels.edit} className="grid size-9 place-items-center rounded-xl border hover:bg-muted" onClick={() => setDialog({ kind: 'question', id: question.id, categoryId: question.category_id, text: question.question_text, type: question.default_type as EnpsQuestionType })} type="button"><Pencil aria-hidden="true" size={14} /></button><button aria-label={labels.delete} className="grid size-9 place-items-center rounded-xl border text-destructive hover:bg-destructive/10" disabled={saving} onClick={() => void remove('questions', question.id)} type="button"><Trash2 aria-hidden="true" size={14} /></button></div> : null}</article>)}{!visible.length ? <p className="rounded-2xl border border-dashed bg-surface p-8 text-center text-sm text-muted-foreground">{labels.empty}</p> : null}</div></section>
    </div>
    {dialog ? <div className="fixed inset-0 z-[90] grid place-items-center bg-sidebar/70 p-4" role="presentation"><div aria-modal="true" className="w-full max-w-xl rounded-3xl border bg-surface p-5 shadow-2xl sm:p-6" role="dialog"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-semibold">{dialog.kind === 'category' ? dialog.id ? labels.editCategory : labels.newCategory : dialog.id ? labels.editQuestion : labels.newQuestion}</h2><button aria-label={labels.cancel} className="grid size-9 place-items-center rounded-xl hover:bg-muted" onClick={() => setDialog(null)} type="button"><X aria-hidden="true" size={18} /></button></div><form className="mt-5 space-y-4" onSubmit={saveDialog}>{dialog.kind === 'category' ? <label className="text-sm font-semibold">{labels.categoryName}<input autoFocus className={inputClass} maxLength={255} minLength={2} onChange={(event) => setDialog({ ...dialog, name: event.target.value })} required value={dialog.name} /></label> : <><div><label className="mb-2 block text-sm font-semibold" htmlFor="bank-category">{labels.category}</label><DropdownSelect id="bank-category" onChange={(event) => setDialog({ ...dialog, categoryId: event.target.value })} searchable value={dialog.categoryId}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</DropdownSelect></div><label className="text-sm font-semibold">{labels.questionText}<textarea autoFocus className={`${inputClass} min-h-28 resize-y`} maxLength={2000} minLength={2} onChange={(event) => setDialog({ ...dialog, text: event.target.value })} required value={dialog.text} /></label><div><label className="mb-2 block text-sm font-semibold" htmlFor="bank-question-type">{labels.questionType}</label><DropdownSelect id="bank-question-type" onChange={(event) => setDialog({ ...dialog, type: event.target.value as EnpsQuestionType })} searchable value={dialog.type}>{Object.entries(labels.typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</DropdownSelect></div></>}<div className="flex justify-end gap-2 pt-2"><button className="button-secondary" onClick={() => setDialog(null)} type="button">{labels.cancel}</button><button className="button-primary" disabled={saving} type="submit">{saving ? labels.saving : labels.save}</button></div></form></div></div> : null}
  </div>
}
