'use client'

import { ArrowDown, ArrowUp, Plus, Save, Trash2 } from 'lucide-react'
import { useRef, useState, type FormEvent } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { DropdownSelect } from '@/components/ui/dropdown-select'
import { Surface } from '@/components/ui/surface'
import { TextInput } from '@/components/ui/text-input'
import { Textarea } from '@/components/ui/textarea'
import { FormField } from '@/components/patterns/form-field'
import { IconButton } from '@/components/ui/icon-button'
import type { ResearchTargetOptions } from '@/lib/research/target-service'
import type { ResearchTargetMode, SurveyQuestionType } from '@/lib/research/schemas'
import type { SurveyDraftData } from '@/lib/research/admin-service'
import { ResearchTargetPicker } from './research-target-picker'

type SurveyQuestionDraft = { key: string; text: string; type: SurveyQuestionType; required: boolean; options: string; rows: string }
interface BuilderLabels { campaign: string; title: string; description: string; startsAt: string; endsAt: string; anonymous: string; target: string; targetMode: string; targetAll: string; targetDepartments: string; targetLocations: string; targetEntities: string; targetEmployees: string; targetSearch: string; targetEmpty: string; selected: string; questions: string; addQuestion: string; question: string; questionText: string; questionType: string; required: string; remove: string; moveUp: string; moveDown: string; options: string; optionPlaceholder: string; matrixRows: string; matrixPlaceholder: string; typeTextSingle: string; typeTextMulti: string; typeSingleChoice: string; typeMultiChoice: string; typeNumber: string; typeDate: string; typeDatetime: string; typeMatrix: string; saveDraft: string; saving: string; saveFailed: string }

function questionLabel(template: string, number: number): string { return template.replace('{number}', String(number)) }
const initialQuestion: SurveyQuestionDraft = { key: '1', text: '', type: 'TEXT_MULTI', required: true, options: '', rows: '' }
function toDateTimeLocal(value: string): string { const date = new Date(value); const pad = (part: number) => String(part).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}` }

export function SurveyBuilder({ labels, targets, draft }: { labels: BuilderLabels; targets: ResearchTargetOptions; draft?: SurveyDraftData }) {
  const router = useRouter()
  const nextKey = useRef(draft ? draft.questions.length + 1 : 2)
  const [title, setTitle] = useState(draft?.title ?? '')
  const [description, setDescription] = useState(draft?.description ?? '')
  const [startsAt, setStartsAt] = useState(draft ? toDateTimeLocal(draft.startsAt) : '')
  const [endsAt, setEndsAt] = useState(draft ? toDateTimeLocal(draft.endsAt) : '')
  const [anonymous, setAnonymous] = useState(draft?.isAnonymous ?? true)
  const [mode, setMode] = useState<ResearchTargetMode>(draft?.targetMode ?? 'ALL')
  const [selectedIds, setSelectedIds] = useState<string[]>(draft?.targetIds ?? [])
  const [questions, setQuestions] = useState<SurveyQuestionDraft[]>(draft?.questions.map((question) => ({ key: question.id, text: question.text, type: question.type, required: question.required, options: question.options.join('\n'), rows: question.rows.map((row) => row.label).join('\n') })) ?? [{ ...initialQuestion }])
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  function updateQuestion(key: string, patch: Partial<SurveyQuestionDraft>): void { setQuestions((current) => current.map((question) => question.key === key ? { ...question, ...patch } : question)) }
  function addQuestion(): void { setQuestions((current) => [...current, { ...initialQuestion, key: String(nextKey.current++), required: false }]) }
  function moveQuestion(index: number, direction: -1 | 1): void { setQuestions((current) => { const target = index + direction; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target]!, next[index]!]; return next }) }
  async function save(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault(); setError(null); setSaving(true)
    try { const response = await fetch(draft ? `/api/research/surveys/${draft.id}` : '/api/research/surveys', { method: draft ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, description, startsAt: new Date(startsAt).toISOString(), endsAt: new Date(endsAt).toISOString(), isAnonymous: anonymous, target: { mode, ids: mode === 'ALL' ? [] : selectedIds }, questions: questions.map((question) => ({ text: question.text, type: question.type, required: question.required, options: question.options.split('\n').map((value) => value.trim()).filter(Boolean), rows: question.rows.split('\n').map((value) => value.trim()).filter(Boolean).map((label) => ({ label, required: question.required })) })) }) }); if (!response.ok) throw new Error('save'); router.push('/settings/research'); router.refresh() } catch { setError(labels.saveFailed) } finally { setSaving(false) }
  }
  const questionTypes: Array<{ value: SurveyQuestionType; label: string }> = [{ value: 'TEXT_SINGLE', label: labels.typeTextSingle }, { value: 'TEXT_MULTI', label: labels.typeTextMulti }, { value: 'SINGLE_CHOICE', label: labels.typeSingleChoice }, { value: 'MULTI_CHOICE', label: labels.typeMultiChoice }, { value: 'NUMBER', label: labels.typeNumber }, { value: 'DATE', label: labels.typeDate }, { value: 'DATETIME', label: labels.typeDatetime }, { value: 'MATRIX', label: labels.typeMatrix }]

  return <form className="space-y-6" onSubmit={(event) => void save(event)}>
    <Surface className="p-5 sm:p-7"><h2 className="text-xl font-semibold">{labels.campaign}</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><FormField className="sm:col-span-2" control={<TextInput maxLength={255} minLength={3} onChange={(event) => setTitle(event.target.value)} required value={title} />} label={labels.title} required /><FormField className="sm:col-span-2" control={<Textarea maxLength={5000} onChange={(event) => setDescription(event.target.value)} value={description} />} label={labels.description} /><FormField control={<TextInput onChange={(event) => setStartsAt(event.target.value)} required type="datetime-local" value={startsAt} />} label={labels.startsAt} required /><FormField control={<TextInput min={startsAt} onChange={(event) => setEndsAt(event.target.value)} required type="datetime-local" value={endsAt} />} label={labels.endsAt} required /></div><Checkbox className="mt-5" checked={anonymous} label={labels.anonymous} onChange={(event) => setAnonymous(event.target.checked)} /></Surface>
    <Surface className="p-5 sm:p-7"><h2 className="text-xl font-semibold">{labels.target}</h2><div className="mt-5"><ResearchTargetPicker labels={{ targetMode: labels.targetMode, targetAll: labels.targetAll, targetDepartments: labels.targetDepartments, targetLocations: labels.targetLocations, targetEntities: labels.targetEntities, targetEmployees: labels.targetEmployees, targetSearch: labels.targetSearch, targetEmpty: labels.targetEmpty, selected: labels.selected }} mode={mode} onModeChange={setMode} onSelectedIdsChange={setSelectedIds} options={targets} selectedIds={selectedIds} /></div></Surface>
    <Surface className="p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-semibold">{labels.questions}</h2><Button onClick={addQuestion} type="button" variant="secondary"><Plus aria-hidden="true" size={16} />{labels.addQuestion}</Button></div><div className="mt-5 space-y-4">{questions.map((question, index) => { const needsOptions = ['SINGLE_CHOICE', 'MULTI_CHOICE', 'MATRIX'].includes(question.type); return <fieldset className="border border-border-subtle bg-surface-subtle p-4 sm:p-5" key={question.key}><legend className="px-2 text-sm font-semibold text-primary">{questionLabel(labels.question, index + 1)}</legend><div className="grid gap-4 sm:grid-cols-2"><FormField className="sm:col-span-2" control={<Textarea maxLength={2000} minLength={2} onChange={(event) => updateQuestion(question.key, { text: event.target.value })} required value={question.text} />} label={labels.questionText} required /><FormField control={<DropdownSelect onChange={(event) => updateQuestion(question.key, { type: event.target.value as SurveyQuestionType })} searchable value={question.type}>{questionTypes.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</DropdownSelect>} label={labels.questionType} /><div className="flex items-end justify-between gap-3 pb-1"><Checkbox checked={question.required} label={labels.required} onChange={(event) => updateQuestion(question.key, { required: event.target.checked })} />{questions.length > 1 ? <Button onClick={() => setQuestions((current) => current.filter((item) => item.key !== question.key))} size="sm" type="button" variant="danger"><Trash2 aria-hidden="true" size={15} />{labels.remove}</Button> : null}</div>{needsOptions ? <FormField className="sm:col-span-2" control={<Textarea onChange={(event) => updateQuestion(question.key, { options: event.target.value })} placeholder={labels.optionPlaceholder} required value={question.options} />} label={labels.options} required /> : null}{question.type === 'MATRIX' ? <FormField className="sm:col-span-2" control={<Textarea onChange={(event) => updateQuestion(question.key, { rows: event.target.value })} placeholder={labels.matrixPlaceholder} required value={question.rows} />} label={labels.matrixRows} required /> : null}</div></fieldset> })}</div></Surface>
    <Surface className="p-4"><p className="text-sm font-semibold">{labels.questions}</p><div className="mt-3 space-y-2">{questions.map((question, index) => <div className="flex items-center gap-3 border border-border-subtle bg-surface-subtle px-3 py-2" key={question.key}><span className="min-w-0 flex-1 truncate text-sm">{index + 1}. {question.text || questionLabel(labels.question, index + 1)}</span><IconButton disabled={index === 0} label={`${labels.moveUp} ${questionLabel(labels.question, index + 1)}`} onClick={() => moveQuestion(index, -1)} size="sm" type="button" variant="secondary"><ArrowUp aria-hidden="true" /></IconButton><IconButton disabled={index === questions.length - 1} label={`${labels.moveDown} ${questionLabel(labels.question, index + 1)}`} onClick={() => moveQuestion(index, 1)} size="sm" type="button" variant="secondary"><ArrowDown aria-hidden="true" /></IconButton></div>)}</div></Surface>
    {error ? <p className="border border-destructive/30 bg-destructive-surface p-4 text-sm font-medium text-destructive" role="alert">{error}</p> : null}<div className="flex justify-end"><Button disabled={saving} loading={saving} type="submit"><Save aria-hidden="true" size={16} />{saving ? labels.saving : labels.saveDraft}</Button></div>
  </form>
}
