import { redirect } from 'next/navigation'
import { AdminSettingsPageHeader } from '@/components/settings/admin-settings-page-header'
import { CompanyDataManager } from '@/components/settings/company-data-manager'
import { AuthorizationError, requirePermission } from '@/lib/auth/permissions'
import { getCompanyDataSettings } from '@/lib/company-data/service'
import { getTranslator } from '@/lib/i18n/server'

export default async function CompanyDataSettingsPage() {
  try { await requirePermission('company-data:read') } catch (error) { if (error instanceof AuthorizationError) redirect('/geen-toegang'); throw error }
  const [initial, t] = await Promise.all([getCompanyDataSettings(), getTranslator('settings')])
  return <main className="mx-auto w-full max-w-7xl px-5 py-8 lg:px-10"><AdminSettingsPageHeader backLabel={t('admin.backToOverview')} eyebrow={t('admin.eyebrow')} subtitle={t('companyData.subtitle')} title={t('companyData.title')} /><CompanyDataManager initial={initial} labels={{ companySection: t('companyData.companySection'), companySectionDescription: t('companyData.companySectionDescription'), locationsSection: t('companyData.locationsSection'), locationsSectionDescription: t('companyData.locationsSectionDescription'), singleLocation: t('companyData.singleLocation'), singleLocationDescription: t('companyData.singleLocationDescription'), singleLocationDisabled: t('companyData.singleLocationDisabled'), save: t('companyData.save'), saving: t('companyData.saving'), saved: t('companyData.saved'), failed: t('companyData.failed'), addLocation: t('companyData.addLocation'), editLocation: t('companyData.editLocation'), locationName: t('companyData.locationName'), locationActive: t('companyData.locationActive'), active: t('companyData.active'), inactive: t('companyData.inactive'), emptyLocations: t('companyData.emptyLocations'), deleteLocation: t('companyData.deleteLocation'), deleteConfirm: t('companyData.deleteConfirm'), locationInUse: t('companyData.locationInUse'), close: t('companyData.close'), cancel: t('companyData.cancel'), country: t('companyData.country'), countrySearch: t('companyData.countrySearch'), countryEmpty: t('companyData.countryEmpty'), addressSearch: t('companyData.addressSearch'), addressSearchPlaceholder: t('companyData.addressSearchPlaceholder'), manualEntry: t('companyData.manualEntry'), searchNoResults: t('companyData.searchNoResults'), searchUnavailable: t('companyData.searchUnavailable'), searchLoading: t('companyData.searchLoading'), lookupByPostalCode: t('companyData.lookupByPostalCode'), lookup: t('companyData.lookup'), lookupHint: t('companyData.lookupHint'), lookupUnavailable: t('companyData.lookupUnavailable'), addressLine1: t('companyData.addressLine1'), addressLine2: t('companyData.addressLine2'), street: t('companyData.street'), houseNumber: t('companyData.houseNumber'), addition: t('companyData.addition'), postalCode: t('companyData.postalCode'), city: t('companyData.city'), region: t('companyData.region'), addressHelp: t('companyData.addressHelp'), genericError: t('companyData.genericError'), companyHasLocations: t('companyData.companyHasLocations'), singleLocationError: t('companyData.singleLocationError') }} /></main>
}
