import Link from 'next/link'
import type { HrChangeEvent, HrChangeEventType } from '@/lib/hr-events/types'

interface Labels { title: string; subtitle: string; empty: string; asOf: string; lanes: Record<'contract'|'organization'|'conditions'|'compensation'|'dossier',string>; events: Record<HrChangeEventType,string> }
const laneFor = (type: HrChangeEventType): keyof Labels['lanes'] => type.startsWith('EMPLOYMENT')||type==='INCOME_RELATIONSHIP_CHANGED'?'contract':type==='ORGANIZATION_CHANGED'?'organization':type==='LABOR_CONDITIONS_CHANGED'||type==='SCHEDULE_CHANGED'?'conditions':type==='SALARY_CHANGED'||type==='COST_ALLOCATION_CHANGED'?'compensation':'dossier'
export function EmploymentTimeMap({ events, selectedDate, labels }: { events: HrChangeEvent[]; selectedDate: string; labels: Labels }) {
  const lanes = Object.keys(labels.lanes) as Array<keyof Labels['lanes']>
  return <section className="rounded-2xl border bg-surface p-5 shadow-sm"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">{labels.title}</h2><p className="mt-1 text-sm text-muted-foreground">{labels.subtitle}</p></div><form className="flex items-end gap-2"><label className="text-sm font-medium">{labels.asOf}<input className="form-field mt-1" defaultValue={selectedDate} name="date" type="date" /></label><button className="button-secondary" type="submit">{labels.asOf}</button></form></header>
    {events.length===0?<p className="mt-5 text-sm text-muted-foreground">{labels.empty}</p>:<><div className="mt-6 hidden overflow-x-auto lg:block"><div className="min-w-[58rem] space-y-2">{lanes.map((lane)=><div className="grid grid-cols-[10rem_repeat(4,minmax(10rem,1fr))] gap-2" key={lane}><div className="sticky left-0 z-10 rounded-xl bg-muted p-3 text-sm font-semibold">{labels.lanes[lane]}</div>{events.filter((event)=>laneFor(event.eventType)===lane).slice(0,4).map((event)=><Link className={`rounded-xl border p-3 text-sm transition hover:bg-muted ${event.eventDate<=selectedDate?'':'opacity-50'}`} href={event.sourceHref} key={event.id}><time className="text-xs font-semibold text-muted-foreground">{event.eventDate}</time><p className="mt-1 font-semibold">{labels.events[event.eventType]}</p></Link>)}</div>)}</div></div><ol className="mt-5 space-y-3 lg:hidden">{events.map((event)=><li key={event.id}><Link className={`block rounded-xl border p-4 ${event.eventDate<=selectedDate?'':'opacity-50'}`} href={event.sourceHref}><div className="flex items-center justify-between gap-3"><span className="status-chip">{labels.lanes[laneFor(event.eventType)]}</span><time className="text-xs text-muted-foreground">{event.eventDate}</time></div><p className="mt-2 font-semibold">{labels.events[event.eventType]}</p></Link></li>)}</ol></>}
  </section>
}
