import { redirect } from 'next/navigation'
import { AdminSettingsPageHeader } from '@/components/settings/admin-settings-page-header'
import { TalentManagementWorkspace, type TalentManagementWorkspaceLabels } from '@/components/talent/talent-management-workspace'
import { AuthorizationError, requirePermission } from '@/lib/auth/permissions'
import { getTranslator } from '@/lib/i18n/server'

export default async function TalentSettingsPage() {
  try { await requirePermission('talent:manage') } catch (error) { if (error instanceof AuthorizationError) redirect('/geen-toegang'); throw error }
  const t = await getTranslator('talent')
  const foundationLabels = {
    code: t('code'), name: t('name'), type: t('type'), status: t('status'), job: t('job'), group: t('group'), family: t('family'), seniority: t('seniority'), levels: t('levels'), models: t('models'), seniorities: t('seniorities'), families: t('families'), categories: t('categories'), capabilities: t('capabilities'), profiles: t('profiles'), empty: t('empty'), addSeniority: t('addSeniority'), addCapability: t('addCapability'), addFamily: t('addFamily'), addCategory: t('addCategory'), addLevel: t('addLevel'), save: t('save'), cancel: t('cancel'), saved: t('saved'), failed: t('failed'), active: t('active'), inactive: t('inactive'), search: t('search'), filterType: t('filterType'), filterCategory: t('filterCategory'), filterTag: t('filterTag'), all: t('all'), edit: t('edit'), delete: t('delete'), confirmDelete: t('confirmDelete'), description: t('description'), capabilityDetails: t('capabilityDetails'), levelContent: t('levelContent'), indicator: t('indicator'), examples: t('examples'), coachingNotes: t('coachingNotes'), tags: t('tags'), languageCode: t('languageCode'), languageCefr: t('languageCefr'), nativeLanguage: t('nativeLanguage'), certificateIssuer: t('certificateIssuer'), certificateValidity: t('certificateValidity'), permanentCertificate: t('permanentCertificate'), certificateCode: t('certificateCode'), renewalRequired: t('renewalRequired'), locked: t('locked'), configurable: t('configurable'), lockedHint: t('lockedHint'), usage: t('usage'), typeCompetency: t('typeCompetency'), typeSkill: t('typeSkill'), typeKnowledge: t('typeKnowledge'), typeLanguage: t('typeLanguage'), typeCertificate: t('typeCertificate'), noResults: t('noResults'), discardTitle: t('assessmentDiscardTitle'), discardDescription: t('assessmentDiscardDescription'), discardConfirm: t('assessmentDiscard'), keepEditing: t('assessmentKeepEditing')
  }
  const profileLabels = {
    profiles: t('profiles'), search: t('search'), all: t('all'), noResults: t('noResults'), empty: t('empty'), library: t('library'), framework: t('framework'), management: t('management'), dashboard: t('dashboard'), counts: t('counts'), recentChanges: t('recentChanges'), attention: t('attention'), draftAttention: t('draftAttention'), missingActive: t('missingActive'), functions: t('functions'), capabilities: t('capabilities'), activeProfiles: t('activeProfiles'), draftVersions: t('draftVersions'), versions: t('versions'), profile: t('profile'), job: t('job'), group: t('group'), family: t('family'), seniority: t('seniority'), status: t('status'), active: t('active'), inactive: t('inactive'), draft: t('draft'), current: t('current'), planned: t('planned'), readOnly: t('readOnly'), newVersion: t('newVersion'), copyVersion: t('copyVersion'), save: t('save'), saved: t('saved'), failed: t('failed'), purpose: t('purpose'), summary: t('summary'), organizationalContext: t('organizationalContext'), tasks: t('tasks'), responsibilities: t('responsibilities'), resultAreas: t('resultAreas'), versionHistory: t('versionHistory'), validFrom: t('validFrom'), validUntil: t('validUntil'), activate: t('activate'), activeDateHint: t('activeDateHint'), requirements: t('requirements'), addRequirement: t('addRequirement'), capability: t('capability'), importance: t('importance'), required: t('required'), important: t('important'), optional: t('optional'), targetLevel: t('targetLevel'), languageLevel: t('languageLevel'), rationale: t('rationale'), remove: t('remove'), noRequirements: t('noRequirements'), profileRequired: t('profileRequired')
  }
  const recordLabels = {
    title: t('personalRecordsTitle'), subtitle: t('personalRecordsSubtitle'), add: t('personalRecordAdd'), edit: t('personalRecordEdit'), save: t('personalRecordSave'), cancel: t('personalRecordCancel'), failed: t('personalRecordFailed'), empty: t('personalRecordEmpty'), noResults: t('personalRecordNoResults'), search: t('personalRecordSearch'), searchPlaceholder: t('personalRecordSearchPlaceholder'), employee: t('personalRecordEmployee'), capability: t('personalRecordCapability'), type: t('personalRecordType'), level: t('personalRecordLevel'), languageLevel: t('personalRecordLanguageLevel'), nativeLanguage: t('personalRecordNativeLanguage'), certificateStatus: t('personalRecordCertificateStatus'), certificateIssuer: t('personalRecordCertificateIssuer'), certificateCode: t('personalRecordCertificateCode'), certificateValidityMonths: t('personalRecordCertificateValidityMonths'), renewalRequired: t('personalRecordRenewalRequired'), evidenceStatus: t('personalRecordEvidenceStatus'), evidenceStatusNotProvided: t('personalRecordEvidenceStatusNotProvided'), evidenceStatusPending: t('personalRecordEvidenceStatusPending'), evidenceStatusVerified: t('personalRecordEvidenceStatusVerified'), evidenceStatusRejected: t('personalRecordEvidenceStatusRejected'), evidenceStatusExpired: t('personalRecordEvidenceStatusExpired'), responsible: t('personalRecordResponsible'), responsibleAssigned: t('personalRecordResponsibleAssigned'), responsibleMissing: t('personalRecordResponsibleMissing'), validFrom: t('personalRecordValidFrom'), validUntil: t('personalRecordValidUntil'), source: t('personalRecordSource'), status: t('personalRecordStatus'), evidence: t('personalRecordEvidence'), evidencePresent: t('personalRecordEvidencePresent'), noEvidence: t('personalRecordNoEvidence'), readOnly: t('personalRecordReadOnly'), draftPolicy: t('personalRecordDraftPolicy'), all: t('personalRecordAll'), validityFilter: t('personalRecordValidityFilter'), expiringSoon: t('personalRecordExpiringSoon'), archiveImpact: t('personalRecordArchiveImpact'), typeCompetency: t('personalRecordTypeCompetency'), typeSkill: t('personalRecordTypeSkill'), typeKnowledge: t('personalRecordTypeKnowledge'), typeLanguage: t('personalRecordTypeLanguage'), typeCertificate: t('personalRecordTypeCertificate'), statusDraft: t('personalRecordStatusDraft'), statusReleased: t('personalRecordStatusReleased'), statusExpired: t('personalRecordStatusExpired'), statusArchived: t('personalRecordStatusArchived'), sourceSelf: t('personalRecordSourceSelf'), sourceHr: t('personalRecordSourceHr'), sourceManager: t('personalRecordSourceManager'), sourceImported: t('personalRecordSourceImported'), certificateValid: t('personalRecordCertificateValid'), certificateExpired: t('personalRecordCertificateExpired'), certificatePermanent: t('personalRecordCertificatePermanent'), certificateRevoked: t('personalRecordCertificateRevoked'), close: t('personalRecordClose')
  }
  const labels: TalentManagementWorkspaceLabels = {
    startTitle: t('startTitle'), startDescription: t('startDescription'), startNavigationTitle: t('startNavigationTitle'), profilesSection: t('profilesSection'), profilesDescription: t('profilesDescription'), recordsSection: t('recordsSection'), recordsDescription: t('recordsDescription'), foundationSection: t('foundationSection'), foundationDescription: t('foundationDescription'), loading: t('loading'), loadFailed: t('loadFailed'), assessmentTitle: t('assessmentTitle'), teamMatrixTitle: t('teamMatrixTitle'), comparisonTitle: t('comparisonTitle'), roleExplorerTitle: t('roleExplorerTitle'), importTitle: t('importTitle'), goalTitle: t('goalTitle'), reportTitle: t('reportTitle'), foundation: foundationLabels, profiles: profileLabels, records: recordLabels, notifications: { title: t('notificationTitle'), intro: t('notificationIntro'), empty: t('notificationEmpty'), markRead: t('notificationMarkRead'), complete: t('notificationComplete'), dismiss: t('notificationDismiss'), saved: t('notificationSaved'), failed: t('notificationFailed') }
  }
  return <section className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><AdminSettingsPageHeader backHref="/settings" backLabel={t('backToSettings')} title={t('settingsTitle')} /><div className="mt-5"><TalentManagementWorkspace labels={labels} /></div></section>
}
