'use client'

import { ArrowLeft, CalendarDays, ShieldAlert } from 'lucide-react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { useState, type ReactElement } from 'react'
import { Badge, type BadgeTone } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { DataTableShell } from '@/components/patterns/data-table-shell'
import { SectionHeader } from '@/components/patterns/section-header'
import { Surface } from '@/components/ui/surface'
import { DropdownSelect } from '@/components/ui/dropdown-select'
import { InsightsActiveFilters, InsightsExportAction, InsightsFilterBar, type InsightActiveFilter } from '@/components/insights/shared-controls'
import { buildInsightApplyHref, insightEmployeeDrilldownHref } from '@/lib/insights/query-seam'
import { defaultLeaveInsightsQuery, leaveInsightsQueryParams } from '@/lib/insights/leave-insights-query'
import type {
  LeaveInsightsAccrualRow,
  LeaveInsightsBalanceRow,
  LeaveInsightsCapacityDayRow,
  LeaveInsightsCapacityRow,
  LeaveInsightsCohortRow,
  LeaveInsightsContractEndRow,
  LeaveInsightsExceptionRow,
  LeaveInsightsFinanceRow,
  LeaveInsightsMutationRow,
  LeaveInsightsQuery,
  LeaveInsightsReport,
  LeaveInsightsUsageRow,
  LeaveInsightsView,
  LeaveInsightsYearCloseRow,
} from '@/lib/insights/leave-insights-types'

type Labels = Readonly<Record<string, string>>

function text(labels: Labels, key: string): string {
  return labels[key] ?? key
}

function hours(value: number | null | undefined, labels: Labels): string {
  return value === null || value === undefined ? text(labels, 'leaveNotAvailable') : value.toLocaleString(undefined, { maximumFractionDigits: 2 })
}

function percentage(value: number, labels?: Labels): string {
  void labels
  return `${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}%`
}

function date(value: string | null, locale: string, labels: Labels): string {
  if (!value) return text(labels, 'leaveNotAvailable')
  return new Intl.DateTimeFormat(locale, { dateStyle: 'medium' }).format(new Date(`${value}T00:00:00Z`))
}

function toneForSeverity(value: string): BadgeTone {
  return value === 'ACTION_REQUIRED' ? 'danger' : value === 'ATTENTION' ? 'warning' : value === 'INFO' ? 'info' : 'neutral'
}

function codeLabel(value: string | null, labels: Labels): string {
  if (!value) return text(labels, 'leaveNotAvailable')
  const translated = labels[`leaveSource${value}`]
  if (translated) return translated
  return value.toLowerCase().split('_').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ')
}

function exceptionDetails(row: LeaveInsightsExceptionRow, labels: Labels): string {
  return row.details === row.code ? text(labels, `leaveException${row.code}`) : row.details
}

function employeeLink(employeeId: string, employeeName: string, returnTo: string): ReactElement {
  return <Link className="text-primary hover:underline" href={insightEmployeeDrilldownHref(employeeId, returnTo, 'leave')}>{employeeName}</Link>
}

function EmptyState({ labels }: { labels: Labels }) {
  return <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">{text(labels, 'leaveNoRows')}</div>
}

function Kpi({ label, value, description, tone = 'default' }: { label: string; value: string; description?: string; tone?: 'default' | 'warning' | 'danger' }) {
  const classes = tone === 'danger' ? 'border-destructive/40 bg-destructive-surface' : tone === 'warning' ? 'border-warning/40 bg-warning-surface' : 'border-border-subtle bg-surface'
  return <Surface className={`p-4 ${classes}`}><p className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{value}</p>{description ? <p className="mt-1 text-sm text-muted-foreground">{description}</p> : null}</Surface>
}

function BalanceTable({ rows, labels, locale, returnTo }: { rows: readonly LeaveInsightsBalanceRow[]; labels: Labels; locale: string; returnTo: string }) {
  void locale
  return <DataTableShell caption={text(labels, 'leaveBalancesTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3">{text(labels, 'leaveType')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveAsOfBalance')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveTakenToDate')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveFuturePlanned')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveFreeToPlan')}</th><th className="px-4 py-3">{text(labels, 'leaveReservoir')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={`${row.employmentId}:${row.leaveTypeId}`}><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3">{row.leaveTypeName}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.asOfBalance, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.takenToDate, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.futurePlanned, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.freeToPlan, labels)}</td><td className="px-4 py-3"><Badge tone={row.reservoirStatus === 'CRITICAL' ? 'danger' : row.reservoirStatus === 'HIGH' ? 'warning' : row.reservoirStatus === 'UNLIMITED' ? 'info' : 'neutral'}>{row.reservoirRatio === null ? text(labels, `leaveReservoir${row.reservoirStatus}`) : `${text(labels, `leaveReservoir${row.reservoirStatus}`)} ${percentage(row.reservoirRatio * 100, labels)}`}</Badge></td></tr>)}</tbody></DataTableShell>
}

function CohortTable({ rows, labels, locale, returnTo }: { rows: readonly LeaveInsightsCohortRow[]; labels: Labels; locale: string; returnTo: string }) {
  return <DataTableShell caption={text(labels, 'leaveExpiryTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3">{text(labels, 'leaveType')}</th><th className="px-4 py-3">{text(labels, 'leaveSourceYear')}</th><th className="px-4 py-3">{text(labels, 'leaveAccrualYear')}</th><th className="px-4 py-3">{text(labels, 'leaveCohort')}</th><th className="px-4 py-3">{text(labels, 'leaveExpiryDate')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveDaysUntilExpiry')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveRemainingHours')}</th><th className="px-4 py-3">{text(labels, 'leaveStatus')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={row.bucketId}><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3">{row.leaveTypeName}</td><td className="px-4 py-3 tabular-nums">{row.sourceAccrualYear}</td><td className="px-4 py-3 tabular-nums">{row.accrualYear}</td><td className="px-4 py-3">{row.cohortKey ?? text(labels, 'leaveNotAvailable')}</td><td className="px-4 py-3">{date(row.expirationDate, locale, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{row.daysUntilExpiration}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.remainingHours, labels)}</td><td className="px-4 py-3"><Badge tone={row.status === 'EXPIRED_REMAINS' ? 'danger' : row.status === 'EXPIRING_SOON' ? 'warning' : 'neutral'}>{text(labels, `leaveCohort${row.status}`)}</Badge></td></tr>)}</tbody></DataTableShell>
}

function UsageTable({ rows, labels, returnTo }: { rows: readonly LeaveInsightsUsageRow[]; labels: Labels; returnTo: string }) {
  return <DataTableShell caption={text(labels, 'leaveUsageTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3">{text(labels, 'leaveType')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveApprovedRequests')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveTakenHours')}</th><th className="px-4 py-3 text-right">{text(labels, 'leavePlannedHours')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveTakenDays')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveHalfDays')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveMultiDayPeriods')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveAveragePeriod')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={`${row.employmentId}:${row.leaveTypeId}`}><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3">{row.leaveTypeName}</td><td className="px-4 py-3 text-right tabular-nums">{row.approvedRequestCount}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.takenHours, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.plannedHours, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{row.takenDays.toLocaleString()}</td><td className="px-4 py-3 text-right tabular-nums">{row.halfDayCount.toLocaleString()}</td><td className="px-4 py-3 text-right tabular-nums">{row.multiDayPeriodCount.toLocaleString()}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.averagePeriodHours, labels)}</td></tr>)}</tbody></DataTableShell>
}

function CapacityTable({ rows, labels, returnTo }: { rows: readonly LeaveInsightsCapacityRow[]; labels: Labels; returnTo: string }) {
  return <DataTableShell caption={text(labels, 'leaveCapacityTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveScheduledHours')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveLeaveHours')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveAvailableHours')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveLeaveRate')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveAnomalies')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={row.employmentId}><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.scheduledHours, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.leaveHours, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.availableHours, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{percentage(row.leaveRate, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{row.nonWorkdayConsumption + row.holidayConsumption}</td></tr>)}</tbody></DataTableShell>
}

function CapacityDayTable({ rows, labels, locale }: { rows: readonly LeaveInsightsCapacityDayRow[]; labels: Labels; locale: string }) {
  return <DataTableShell caption={text(labels, 'leaveCapacityByDay')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'leaveDate')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveScheduledHours')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveLeaveHours')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveAvailableHours')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveLeaveRate')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveCapacityEmployees')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveCapacityLeaveEmployees')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={row.date}><td className="px-4 py-3">{date(row.date, locale, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.scheduledHours, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.leaveHours, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.availableHours, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{percentage(row.leaveRate, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{row.employeeCount}</td><td className="px-4 py-3 text-right tabular-nums">{row.leaveEmployeeCount}</td></tr>)}</tbody></DataTableShell>
}

function AccrualTable({ rows, labels, locale, returnTo }: { rows: readonly LeaveInsightsAccrualRow[]; labels: Labels; locale: string; returnTo: string }) {
  return <DataTableShell caption={text(labels, 'leaveAccrualTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3">{text(labels, 'leaveType')}</th><th className="px-4 py-3">{text(labels, 'leaveProfile')}</th><th className="px-4 py-3">{text(labels, 'leaveRule')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveAnnualFullTime')}</th><th className="px-4 py-3 text-right">{text(labels, 'leavePartTimeFactor')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveEffectiveEntitlement')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveAccruedToDate')}</th><th className="px-4 py-3">{text(labels, 'leaveMigrationCutover')}</th><th className="px-4 py-3">{text(labels, 'leaveNoAccrual')}</th><th className="px-4 py-3">{text(labels, 'leavePauseTypes')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={`${row.employmentId}:${row.leaveTypeId}`}><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3">{row.leaveTypeName}</td><td className="px-4 py-3">{row.profileName ?? text(labels, 'leaveMissingProfile')}</td><td className="px-4 py-3">{row.ruleId ?? text(labels, 'leaveMissingRule')}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.annualFullTimeEntitlement, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{row.partTimeFactor === null ? text(labels, 'leaveNotAvailable') : percentage(row.partTimeFactor * 100, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.effectiveEntitlement, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.accruedToDate, labels)}</td><td className="px-4 py-3">{date(row.migrationCutoverDate, locale, labels)}</td><td className="px-4 py-3">{row.noAccrual ? text(labels, 'leaveYes') : text(labels, 'leaveNo')}</td><td className="px-4 py-3">{row.pauseLeaveTypeNames.length ? row.pauseLeaveTypeNames.join(', ') : text(labels, 'leaveNotAvailable')}</td></tr>)}</tbody></DataTableShell>
}

function MutationTable({ rows, labels, locale, returnTo }: { rows: readonly LeaveInsightsMutationRow[]; labels: Labels; locale: string; returnTo: string }) {
  return <DataTableShell caption={text(labels, 'leaveMutationsTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'leaveDate')}</th><th className="px-4 py-3">{text(labels, 'leaveCreatedAt')}</th><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3">{text(labels, 'leaveType')}</th><th className="px-4 py-3">{text(labels, 'leaveMutationClass')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveAmount')}</th><th className="px-4 py-3">{text(labels, 'leaveSourceType')}</th><th className="px-4 py-3">{text(labels, 'leaveSourceKey')}</th><th className="px-4 py-3">{text(labels, 'leaveCohort')}</th><th className="px-4 py-3">{text(labels, 'leaveAccrualYear')}</th><th className="px-4 py-3">{text(labels, 'leaveActor')}</th><th className="px-4 py-3">{text(labels, 'leaveReason')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={row.id}><td className="px-4 py-3">{date(row.transactionDate, locale, labels)}</td><td className="px-4 py-3 text-sm">{row.createdAt ? new Intl.DateTimeFormat(locale, { dateStyle: 'medium' }).format(new Date(row.createdAt)) : text(labels, 'leaveNotAvailable')}</td><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3">{row.leaveTypeName}</td><td className="px-4 py-3"><Badge>{text(labels, `leaveMutation${row.transactionType}`)}</Badge></td><td className="px-4 py-3 text-right tabular-nums">{hours(row.amount, labels)}</td><td className="px-4 py-3">{codeLabel(row.sourceType, labels)}</td><td className="max-w-xs truncate px-4 py-3 font-mono text-xs">{row.sourceKey ?? text(labels, 'leaveNotAvailable')}</td><td className="px-4 py-3">{row.cohortKey ?? text(labels, 'leaveNotAvailable')}</td><td className="px-4 py-3 tabular-nums">{row.accrualYear ?? text(labels, 'leaveNotAvailable')}</td><td className="px-4 py-3">{row.actorDisplayName ?? text(labels, 'leaveSystemActor')}</td><td className="max-w-xs truncate px-4 py-3 text-muted-foreground">{row.reason ?? text(labels, 'leaveNoReason')}</td></tr>)}</tbody></DataTableShell>
}

function FinanceTable({ rows, labels, locale, returnTo }: { rows: readonly LeaveInsightsFinanceRow[]; labels: Labels; locale: string; returnTo: string }) {
  return <DataTableShell caption={text(labels, 'leaveFinanceTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3">{text(labels, 'leaveType')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveValuationHours')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveHourlyRate')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveLiability')}</th><th className="px-4 py-3">{text(labels, 'leaveValuationStatus')}</th><th className="px-4 py-3">{text(labels, 'leaveValuationDate')}</th><th className="px-4 py-3">{text(labels, 'leaveBasis')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={`${row.employmentId}:${row.leaveTypeId}`}><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3">{row.leaveTypeName}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.hours, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{row.hourlyRate === null ? text(labels, 'leaveNotAvailable') : row.hourlyRate.toLocaleString(undefined, { maximumFractionDigits: 2 })}</td><td className="px-4 py-3 text-right tabular-nums">{row.liabilityAmount === null ? text(labels, 'leaveNotAvailable') : row.liabilityAmount.toLocaleString(undefined, { maximumFractionDigits: 2 })}</td><td className="px-4 py-3"><Badge tone={row.valuationStatus === 'VALUED' ? 'success' : 'warning'}>{text(labels, `leaveValuation${row.valuationStatus}`)}</Badge></td><td className="px-4 py-3">{date(row.valuationDate, locale, labels)}</td><td className="px-4 py-3">{row.basisLabel ?? text(labels, 'leaveNotAvailable')}</td></tr>)}</tbody></DataTableShell>
}

function ContractEndTable({ rows, labels, locale, returnTo }: { rows: readonly LeaveInsightsContractEndRow[]; labels: Labels; locale: string; returnTo: string }) {
  return <DataTableShell caption={text(labels, 'leaveContractEndTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3">{text(labels, 'leaveContractEndDate')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveDaysUntilContractEnd')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveBalanceAtAsOf')}</th><th className="px-4 py-3 text-right">{text(labels, 'leavePlannedThroughEnd')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveBalanceAtEnd')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={row.employmentId}><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3">{date(row.contractEndDate, locale, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{row.daysUntilContractEnd}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.balanceAtAsOf, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.plannedThroughContractEnd, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.balanceAtContractEnd, labels)}</td></tr>)}</tbody></DataTableShell>
}

function YearCloseTable({ rows, labels, returnTo }: { rows: readonly LeaveInsightsYearCloseRow[]; labels: Labels; returnTo: string }) {
  return <DataTableShell caption={text(labels, 'leaveYearCloseTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3">{text(labels, 'leaveType')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveLedgerBalance')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveBucketBalance')}</th><th className="px-4 py-3 text-right">{text(labels, 'leaveDifference')}</th><th className="px-4 py-3">{text(labels, 'leaveStatus')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row) => <tr key={`${row.employmentId}:${row.leaveTypeId}`}><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3">{row.leaveTypeName}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.ledgerBalance, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.bucketBalance, labels)}</td><td className="px-4 py-3 text-right tabular-nums">{hours(row.difference, labels)}</td><td className="px-4 py-3"><Badge tone={row.status === 'MISMATCH' ? 'danger' : row.status === 'NOT_LOCKED' ? 'warning' : 'success'}>{text(labels, `leaveYearClose${row.status}`)}</Badge></td></tr>)}</tbody></DataTableShell>
}

function ExceptionTable({ rows, labels, returnTo }: { rows: readonly LeaveInsightsExceptionRow[]; labels: Labels; returnTo: string }) {
  return <DataTableShell caption={text(labels, 'leaveExceptionsTitle')} state={rows.length ? 'ready' : 'empty'} stateContent={<EmptyState labels={labels} />}><thead className="bg-surface-subtle text-xs uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-4 py-3">{text(labels, 'employee')}</th><th className="px-4 py-3">{text(labels, 'leaveType')}</th><th className="px-4 py-3">{text(labels, 'leaveExceptionCode')}</th><th className="px-4 py-3">{text(labels, 'leaveSeverity')}</th><th className="px-4 py-3">{text(labels, 'leaveDetails')}</th></tr></thead><tbody className="divide-y divide-border-subtle">{rows.map((row, index) => <tr key={`${row.employmentId}:${row.code}:${row.leaveTypeId ?? 'none'}:${index}`}><td className="px-4 py-3 font-medium">{employeeLink(row.employeeId, row.employeeName, returnTo)}</td><td className="px-4 py-3">{row.leaveTypeName ?? text(labels, 'leaveNotAvailable')}</td><td className="px-4 py-3">{text(labels, `leaveException${row.code}`)}</td><td className="px-4 py-3"><Badge tone={toneForSeverity(row.severity)}>{text(labels, `leaveSeverity${row.severity}`)}</Badge></td><td className="px-4 py-3 text-muted-foreground">{exceptionDetails(row, labels)}</td></tr>)}</tbody></DataTableShell>
}

function currentReturnTo(query: LeaveInsightsQuery): string {
  const params = leaveInsightsQueryParams(query)
  return `/insights?${params.toString()}`
}

export function LeaveInsightsReportView({ report, query, labels, locale, returnTo }: { report: LeaveInsightsReport; query: LeaveInsightsQuery; labels: Labels; locale: string; returnTo: string }) {
  const router = useRouter()
  const searchParams = useSearchParams()
  const [draft, setDraft] = useState(query)
  const apply = (next: LeaveInsightsQuery): void => {
    const href = buildInsightApplyHref(new URLSearchParams(searchParams.toString()), leaveInsightsQueryParams(next))
    router.push(href, { scroll: false })
  }
  const reset = (): void => apply(defaultLeaveInsightsQuery())
  const viewOptions: Array<{ value: LeaveInsightsView; label: string }> = [
    { value: 'overview', label: text(labels, 'leaveViewOverview') }, { value: 'balances', label: text(labels, 'leaveViewBalances') }, { value: 'expiry', label: text(labels, 'leaveViewExpiry') }, { value: 'usage', label: text(labels, 'leaveViewUsage') }, { value: 'capacity', label: text(labels, 'leaveViewCapacity') }, { value: 'accrual', label: text(labels, 'leaveViewAccrual') }, { value: 'mutations', label: text(labels, 'leaveViewMutations') }, { value: 'finance', label: text(labels, 'leaveViewFinance') }, { value: 'contract-end', label: text(labels, 'leaveViewContractEnd') }, { value: 'year-close', label: text(labels, 'leaveViewYearClose') }, { value: 'exceptions', label: text(labels, 'leaveViewExceptions') },
  ]
  const activeFilters: InsightActiveFilter[] = [
    { key: 'asOfDate', label: text(labels, 'leaveAsOfDate'), value: date(draft.asOfDate, locale, labels), onRemove: () => apply({ ...draft, asOfDate: defaultLeaveInsightsQuery().asOfDate }) },
    ...(draft.departmentId ? [{ key: 'departmentId', label: text(labels, 'leaveDepartment'), value: report.filterOptions.departments.find((item) => item.value === draft.departmentId)?.label ?? draft.departmentId, onRemove: () => apply({ ...draft, departmentId: null }) }] : []),
    ...(draft.managerId ? [{ key: 'managerId', label: text(labels, 'leaveManager'), value: report.filterOptions.managers.find((item) => item.value === draft.managerId)?.label ?? draft.managerId, onRemove: () => apply({ ...draft, managerId: null }) }] : []),
    ...(draft.leaveTypeId ? [{ key: 'leaveTypeId', label: text(labels, 'leaveType'), value: report.filterOptions.leaveTypes.find((item) => item.value === draft.leaveTypeId)?.label ?? draft.leaveTypeId, onRemove: () => apply({ ...draft, leaveTypeId: null }) }] : []),
    ...(draft.profileId ? [{ key: 'profileId', label: text(labels, 'leaveProfile'), value: report.filterOptions.profiles.find((item) => item.value === draft.profileId)?.label ?? draft.profileId, onRemove: () => apply({ ...draft, profileId: null }) }] : []),
    ...(draft.severity ? [{ key: 'severity', label: text(labels, 'leaveSeverity'), value: text(labels, `leaveSeverity${draft.severity}`), onRemove: () => apply({ ...draft, severity: null }) }] : []),
  ]
  const exportParams = leaveInsightsQueryParams(query, 'csv')
  const scopedReturnTo = returnTo || currentReturnTo(query)
  const content = query.view === 'balances' ? <BalanceTable labels={labels} locale={locale} returnTo={scopedReturnTo} rows={report.balances} />
    : query.view === 'expiry' ? <CohortTable labels={labels} locale={locale} returnTo={scopedReturnTo} rows={report.cohorts} />
      : query.view === 'usage' ? <UsageTable labels={labels} returnTo={scopedReturnTo} rows={report.usage} />
        : query.view === 'capacity' ? <div className="space-y-4"><CapacityDayTable labels={labels} locale={locale} rows={report.capacityDays} /><CapacityTable labels={labels} returnTo={scopedReturnTo} rows={report.capacity} /></div>
          : query.view === 'accrual' ? <AccrualTable labels={labels} locale={locale} returnTo={scopedReturnTo} rows={report.accrual} />
              : query.view === 'mutations' ? <MutationTable labels={labels} locale={locale} returnTo={scopedReturnTo} rows={report.mutations} />
                : query.view === 'finance' ? <div className="space-y-4">{!report.financeAvailable ? <Surface className="flex items-start gap-3 p-4 text-sm text-muted-foreground" variant="subtle"><ShieldAlert aria-hidden="true" className="mt-0.5 shrink-0 text-warning" size={17} /><p>{text(labels, 'leaveFinanceUnavailable')}</p></Surface> : null}<FinanceTable labels={labels} locale={locale} returnTo={scopedReturnTo} rows={report.finance} /></div>
                : query.view === 'contract-end' ? <ContractEndTable labels={labels} locale={locale} returnTo={scopedReturnTo} rows={report.contractEnd} />
                  : query.view === 'year-close' ? <YearCloseTable labels={labels} returnTo={scopedReturnTo} rows={report.yearClose} />
                    : query.view === 'exceptions' ? <ExceptionTable labels={labels} returnTo={scopedReturnTo} rows={report.exceptions} />
                      : <BalanceTable labels={labels} locale={locale} returnTo={scopedReturnTo} rows={report.balances} />
  return <section className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link className="inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline" href="/insights"><ArrowLeft aria-hidden="true" size={16} />{text(labels, 'backToInsights')}</Link><span className="inline-flex items-center gap-2 text-sm text-muted-foreground"><CalendarDays aria-hidden="true" size={16} />{text(labels, 'leaveAsOfLabel')} {date(query.asOfDate, locale, labels)}</span></div>
    <header><p className="eyebrow">{text(labels, 'leaveInsightsEyebrow')}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">{text(labels, 'leaveInsightsTitle')}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{text(labels, 'leaveInsightsDescription')}</p></header>
    <nav aria-label={text(labels, 'leaveViewLabel')} className="flex gap-2 overflow-x-auto border-b border-border-subtle pb-2">{viewOptions.map((option) => <button aria-current={query.view === option.value ? 'page' : undefined} className={`whitespace-nowrap rounded-md px-3 py-2 text-sm font-medium ${query.view === option.value ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:text-foreground'}`} key={option.value} onClick={() => apply({ ...draft, view: option.value })} type="button">{option.label}</button>)}</nav>
    <InsightsFilterBar actions={<><Button onClick={() => apply(draft)} size="md" type="button">{text(labels, 'applyFilters')}</Button><Button onClick={reset} size="md" type="button" variant="secondary">{text(labels, 'resetFilters')}</Button><InsightsExportAction fileName={`leave-insights-${query.view}-${query.year}.csv`} href={`/api/insights/leave?${exportParams.toString()}`} label={text(labels, 'exportCsv')} labels={{ error: text(labels, 'exportFailed'), loading: text(labels, 'exportPreparing'), success: text(labels, 'exportSuccess') }} /></>}>
      <label className="flex min-w-32 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leaveViewLabel')}</span><DropdownSelect aria-label={text(labels, 'leaveViewLabel')} onChange={(event) => setDraft((current) => ({ ...current, view: event.currentTarget.value as LeaveInsightsView }))} value={draft.view}>{viewOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</DropdownSelect></label>
      <label className="flex min-w-24 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leaveYear')}</span><input aria-label={text(labels, 'leaveYear')} className="min-h-10 rounded-[var(--radius-control)] border border-border bg-surface px-3 text-sm" max="2100" min="2000" onChange={(event) => setDraft((current) => ({ ...current, year: Number(event.currentTarget.value) || current.year }))} type="number" value={draft.year} /></label>
      <label className="flex min-w-40 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leaveAsOfDate')}</span><input aria-label={text(labels, 'leaveAsOfDate')} className="min-h-10 rounded-[var(--radius-control)] border border-border bg-surface px-3 text-sm" onChange={(event) => setDraft((current) => ({ ...current, asOfDate: event.currentTarget.value }))} type="date" value={draft.asOfDate} /></label>
      <label className="flex min-w-40 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leavePeriodStart')}</span><input aria-label={text(labels, 'leavePeriodStart')} className="min-h-10 rounded-[var(--radius-control)] border border-border bg-surface px-3 text-sm" onChange={(event) => setDraft((current) => ({ ...current, periodStart: event.currentTarget.value }))} type="date" value={draft.periodStart} /></label>
      <label className="flex min-w-40 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leavePeriodEnd')}</span><input aria-label={text(labels, 'leavePeriodEnd')} className="min-h-10 rounded-[var(--radius-control)] border border-border bg-surface px-3 text-sm" onChange={(event) => setDraft((current) => ({ ...current, periodEnd: event.currentTarget.value }))} type="date" value={draft.periodEnd} /></label>
      <label className="flex min-w-48 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leaveDepartment')}</span><DropdownSelect aria-label={text(labels, 'leaveDepartment')} onChange={(event) => setDraft((current) => ({ ...current, departmentId: event.currentTarget.value || null }))} searchable searchPlaceholder={text(labels, 'searchOptions')} value={draft.departmentId ?? ''}><option value="">{text(labels, 'leaveAllDepartments')}</option>{report.filterOptions.departments.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</DropdownSelect></label>
      <label className="flex min-w-48 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leaveManager')}</span><DropdownSelect aria-label={text(labels, 'leaveManager')} onChange={(event) => setDraft((current) => ({ ...current, managerId: event.currentTarget.value || null }))} searchable searchPlaceholder={text(labels, 'searchOptions')} value={draft.managerId ?? ''}><option value="">{text(labels, 'leaveAllManagers')}</option>{report.filterOptions.managers.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</DropdownSelect></label>
      <label className="flex min-w-48 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leaveType')}</span><DropdownSelect aria-label={text(labels, 'leaveType')} onChange={(event) => setDraft((current) => ({ ...current, leaveTypeId: event.currentTarget.value || null }))} searchable searchPlaceholder={text(labels, 'searchOptions')} value={draft.leaveTypeId ?? ''}><option value="">{text(labels, 'leaveAllTypes')}</option>{report.filterOptions.leaveTypes.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</DropdownSelect></label>
      <label className="flex min-w-48 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leaveProfile')}</span><DropdownSelect aria-label={text(labels, 'leaveProfile')} onChange={(event) => setDraft((current) => ({ ...current, profileId: event.currentTarget.value || null }))} searchable searchPlaceholder={text(labels, 'searchOptions')} value={draft.profileId ?? ''}><option value="">{text(labels, 'leaveAllProfiles')}</option>{report.filterOptions.profiles.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</DropdownSelect></label>
      <label className="flex min-w-44 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leaveSeverity')}</span><DropdownSelect aria-label={text(labels, 'leaveSeverity')} onChange={(event) => setDraft((current) => ({ ...current, severity: event.currentTarget.value ? event.currentTarget.value as LeaveInsightsQuery['severity'] : null }))} value={draft.severity ?? ''}><option value="">{text(labels, 'leaveAllSeverities')}</option><option value="INFO">{text(labels, 'leaveSeverityINFO')}</option><option value="ATTENTION">{text(labels, 'leaveSeverityATTENTION')}</option><option value="ACTION_REQUIRED">{text(labels, 'leaveSeverityACTION_REQUIRED')}</option></DropdownSelect></label>
      <label className="flex min-w-32 flex-1 flex-col gap-1.5 text-sm font-medium"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground">{text(labels, 'leaveReservoirThreshold')}</span><input aria-label={text(labels, 'leaveReservoirThreshold')} className="min-h-10 rounded-[var(--radius-control)] border border-border bg-surface px-3 text-sm" max="1" min="0.05" onChange={(event) => setDraft((current) => ({ ...current, reservoirThreshold: Number(event.currentTarget.value) || current.reservoirThreshold }))} step="0.05" type="number" value={draft.reservoirThreshold} /></label>
     </InsightsFilterBar>
    <InsightsActiveFilters clearLabel={text(labels, 'clearFilters')} filters={activeFilters} label={text(labels, 'activeFilters')} onClear={reset} onReset={reset} removeLabel={text(labels, 'removeFilter')} resetLabel={text(labels, 'resetFilters')} />
     <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label={text(labels, 'leaveKpiEmployees')} value={String(report.kpis.employees)} /><Kpi label={text(labels, 'leaveKpiBalance')} value={hours(report.kpis.balanceHours, labels)} description={text(labels, 'leaveHoursUnit')} /><Kpi label={text(labels, 'leaveKpiTaken')} value={hours(report.kpis.takenHours, labels)} description={text(labels, 'leaveHoursUnit')} /><Kpi label={text(labels, 'leaveKpiFuturePlanned')} value={hours(report.kpis.futurePlannedHours, labels)} description={text(labels, 'leaveHoursUnit')} /><Kpi label={text(labels, 'leaveKpiExpiring90')} value={hours(report.kpis.expiring90Hours, labels)} description={text(labels, 'leaveHoursUnit')} tone={report.kpis.expiring90Hours ? 'warning' : 'default'} /><Kpi label={text(labels, 'leaveKpiCarryForward')} value={hours(report.kpis.carryForwardHours, labels)} description={text(labels, 'leaveHoursUnit')} /><Kpi label={text(labels, 'leaveKpiReservoirSignals')} value={String(report.kpis.employeesWithReservoirSignal)} tone={report.kpis.employeesWithReservoirSignal ? 'warning' : 'default'} /><Kpi label={text(labels, 'leaveKpiExceptions')} value={String(report.kpis.exceptionCount)} tone={report.kpis.exceptionCount ? 'warning' : 'default'} /><Kpi label={text(labels, 'leaveKpiNoTaken')} value={String(report.kpis.employeesWithoutTakenLeave)} /><Kpi label={text(labels, 'leaveKpiNoFuture')} value={String(report.kpis.employeesWithoutFutureLeave)} /><Kpi label={text(labels, 'leaveKpiContractEnds')} value={String(report.kpis.contractsEndingWithBalance)} tone={report.kpis.contractsEndingWithBalance ? 'warning' : 'default'} /></div>
     <p className="text-xs text-muted-foreground">{text(labels, 'leaveAnalyticalThreshold')} {percentage(query.reservoirThreshold * 100, labels)}</p>
    {query.view === 'overview' ? <Surface className="p-4 text-sm leading-6 text-muted-foreground" variant="subtle"><p>{text(labels, 'leaveOverviewExplanation')}</p><p className="mt-2">{text(labels, 'leaveAsOfExplanation').replace('{date}', date(query.asOfDate, locale, labels))}</p></Surface> : null}
    <SectionHeader description={`${text(labels, 'leavePeriodLabel')} ${date(query.periodStart, locale, labels)} – ${date(query.periodEnd, locale, labels)}`} title={text(labels, query.view === 'overview' ? 'leaveOverviewTitle' : `leaveView${query.view === 'contract-end' ? 'ContractEnd' : query.view === 'year-close' ? 'YearClose' : query.view.charAt(0).toUpperCase() + query.view.slice(1)}`)} />
    {content}
  </section>
}
