import { createHash } from 'node:crypto'
import type { CanonicalBlock, CanonicalDocument, CanonicalInline, CanonicalRegions } from '@/lib/document-studio/canonical-document'

export type GenerationValues = Readonly<Record<string, string>>
export interface GenerationContext { readonly tenantId: string; readonly hrGroupId: string; readonly employeeId: string; readonly templateId: string; readonly templateVersionId: string; readonly templateVersion: number; readonly rendererVersion: string; readonly generatedAt: string; readonly knownValues: GenerationValues; readonly temporalValues: GenerationValues; readonly freeValues: GenerationValues; readonly documentProfile: Readonly<Record<string, unknown>>; readonly organization: Readonly<Record<string, unknown>>; readonly componentVersions: readonly { readonly kind: 'COVER' | 'APPENDIX'; readonly templateVersionId: string; readonly version: number }[] }
export interface ResolvedGenerationSnapshot extends GenerationContext { readonly resolvedDocument: CanonicalDocument; readonly resolvedDocumentJson: string; readonly resolvedDocumentHash: string; readonly placeholderInputs: Readonly<{ known: GenerationValues; temporal: GenerationValues; free: GenerationValues }> }
function resolveInline(nodes: readonly CanonicalInline[], context: GenerationContext): CanonicalInline[] { return nodes.map((node) => { if (node.type === 'text') return { ...node }; if (node.type === 'knownPlaceholder') return { type: 'text', text: context.knownValues[node.attrs.field] ?? '' }; if (node.type === 'temporalPlaceholder') return { type: 'text', text: context.temporalValues[`${node.attrs.field}[${node.attrs.temporal}]`] ?? '' }; return { type: 'text', text: context.freeValues[node.attrs.key] ?? '' } }) }
function resolveBlocks(blocks: readonly CanonicalBlock[], context: GenerationContext): CanonicalBlock[] { return blocks.map((block) => { if (block.type === 'paragraph' || block.type === 'heading') return { ...block, content: resolveInline(block.content, context) }; if (block.type === 'bulletList' || block.type === 'orderedList') return { ...block, content: block.content.map((item) => ({ ...item, content: item.content.map((paragraph) => ({ ...paragraph, content: resolveInline(paragraph.content, context) })) })) }; if (block.type === 'table') return { ...block, content: block.content.map((row) => ({ ...row, content: row.content.map((cell) => ({ ...cell, content: cell.content.map((paragraph) => ({ ...paragraph, content: resolveInline(paragraph.content, context) })) })) })) }; if (block.type === 'twoColumnBlock') return { ...block, content: block.content.map((column) => ({ ...column, content: resolveBlocks(column.content, context) })) as unknown as typeof block.content }; return { ...block } }) }
function resolveRegions(regions: CanonicalRegions, context: GenerationContext): CanonicalRegions { return Object.fromEntries(Object.entries(regions).map(([key, region]) => [key, region ? { ...region, content: resolveBlocks(region.content, context) } : null])) as CanonicalRegions }
export function resolveGenerationSnapshot(document: CanonicalDocument, context: GenerationContext): ResolvedGenerationSnapshot { const resolvedDocument = { ...document, regions: resolveRegions(document.regions, context) }; const resolvedDocumentJson = JSON.stringify(resolvedDocument); return { ...context, resolvedDocument, resolvedDocumentJson, resolvedDocumentHash: createHash('sha256').update(resolvedDocumentJson).digest('hex'), placeholderInputs: { known: { ...context.knownValues }, temporal: { ...context.temporalValues }, free: { ...context.freeValues } } } }
export function assertActiveComponentVersions(requested: readonly { readonly kind: 'COVER' | 'APPENDIX'; readonly templateVersionId: string; readonly version: number }[], active: readonly { readonly kind: 'COVER' | 'APPENDIX'; readonly templateVersionId: string; readonly version: number }[]): void { if (JSON.stringify(requested) !== JSON.stringify(active)) throw new Error('DOCUMENT_GENERATION_COMPONENT_VERSION_NOT_ACTIVE') }
