import { redirect } from 'next/navigation'
import { AdminSettingsPageHeader } from '@/components/settings/admin-settings-page-header'
import { TalentReportWorkspace } from '@/components/talent/talent-report-workspace'
import { AuthorizationError, requirePermission } from '@/lib/auth/permissions'
import { getTranslator } from '@/lib/i18n/server'
import { listTalentReport } from '@/lib/talent/report-service'
import { parseTalentReportQuery } from '@/lib/talent/report-schemas'

export default async function TalentReportsSettingsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  try { await requirePermission('talent-report:read') } catch (error) { if (error instanceof AuthorizationError) redirect('/geen-toegang'); throw error }
  const query = parseTalentReportQuery('admin', await searchParams)
  const [initial, t] = await Promise.all([listTalentReport('admin', query), getTranslator('talent')])
  const labels = { title: t('reportTitle'), subtitle: t('reportAdminSubtitle'), export: t('reportExport'), exportFailed: t('reportExportFailed'), exporting: t('reportExporting'), filterFailed: t('reportFilterFailed'), periodInvalid: t('reportPeriodInvalid'), goals: t('reportGoals'), capabilities: t('reportCapabilities'), empty: t('reportEmpty'), noResults: t('reportNoResults'), employee: t('reportEmployee'), goalOrCapability: t('reportGoalOrCapability'), status: t('reportStatus'), progress: t('reportProgress'), period: t('reportPeriod'), validity: t('reportValidity'), type: t('reportType'), source: t('reportSource'), evidence: t('reportEvidence'), level: t('reportLevel'), all: t('reportAll'), loading: t('reportLoading'), current: t('reportCurrent'), history: t('reportHistory'), filterMode: t('reportFilterMode'), modeAll: t('reportModeAll'), modeGoals: t('reportModeGoals'), modeCapabilities: t('reportModeCapabilities'), timeframe: t('reportTimeframe'), timeframeAll: t('reportTimeframeAll'), activeFilters: t('reportActiveFilters'), resetFilters: t('reportResetFilters'), scopeTenant: t('reportScopeTenant'), scopeManager: t('reportScopeManager'), scopeSelf: t('reportScopeSelf'), employees: t('reportEmployees'), rows: t('reportRows'), notAvailable: t('reportNotAvailable'), statusDraft: t('goalDraft'), statusActive: t('goalActive'), statusCompleted: t('goalCompleted'), statusCancelled: t('goalCancelled'), statusArchived: t('goalArchived'), recordDraft: t('personalRecordStatusDraft'), recordReleased: t('personalRecordStatusReleased'), recordExpired: t('personalRecordStatusExpired'), recordArchived: t('personalRecordStatusArchived'), sourceSelf: t('personalRecordSourceSelf'), sourceHr: t('personalRecordSourceHr'), sourceManager: t('personalRecordSourceManager'), sourceImported: t('personalRecordSourceImported'), periodFrom: t('reportPeriodFrom'), periodTo: t('reportPeriodTo'), applyFilters: t('reportApplyFilters'), population: t('reportPopulation') }
  return <section className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><AdminSettingsPageHeader backHref="/settings/talent" backLabel={t('backToTalent')} title={t('reportTitle')} subtitle={t('reportAdminSubtitle')} /><TalentReportWorkspace mode="admin" initial={initial} labels={labels} /></section>
}
