'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { Bell, CalendarDays, Clock3, X } from 'lucide-react'
import { buildMonthDays, groupEventsByEmployee } from '@/lib/hr-calendar/calendar-model'
import type { HrChangeEvent, HrChangeEventType } from '@/lib/hr-events/types'
import type { CalendarReminder, CalendarWorkDay } from '@/lib/hr-calendar/calendar-service'

interface Employee { id:string;employee_number:string;first_name:string;birth_name:string;avatar_url:string|null;departmentId:string|null;averageMinutesPerWeek:number;workDays:Record<string,CalendarWorkDay> }
interface Holiday { id:string;holiday_date:string;display_name:string|null;provider_name:string;source:string }
interface Labels { noEvents:string;workHours:string;nonWorking:string;hoursPerWeek:string;holiday:string;reminder:string;dayDetails:string;employeeDayDetails:string;actionsLater:string;close:string;events:Record<HrChangeEventType,string> }
type Selection = { type:'day';date:string } | { type:'employee';date:string;employee:Employee } | null

export function HrMonthCalendar({month,employees,events,holidays,reminders,generalReminders,labels}:{month:string;employees:Employee[];events:HrChangeEvent[];holidays:Holiday[];reminders:CalendarReminder[];generalReminders:CalendarReminder[];labels:Labels}) {
  const days=buildMonthDays(month); const grouped=groupEventsByEmployee(events); const [selection,setSelection]=useState<Selection>(null)
  const holidayByDate=useMemo(()=>new Map(holidays.map((holiday)=>[holiday.holiday_date,holiday])),[holidays])
  const remindersByEmployee=useMemo(()=>{const result=new Map<string,Map<string,CalendarReminder[]>>();for(const reminder of reminders){if(!reminder.employeeId)continue;const byDate=result.get(reminder.employeeId)??new Map<string,CalendarReminder[]>();byDate.set(reminder.date,[...(byDate.get(reminder.date)??[]),reminder]);result.set(reminder.employeeId,byDate)}return result},[reminders])
  const selectedEmployeeEvents=selection?.type==='employee'?grouped.get(selection.employee.id)?.get(selection.date)??[]:[]
  const selectedEmployeeReminders=selection?.type==='employee'?remindersByEmployee.get(selection.employee.id)?.get(selection.date)??[]:[]
  const selectedWorkDay=selection?.type==='employee'?selection.employee.workDays[selection.date]:undefined
  const selectedHoliday=selection?holidayByDate.get(selection.date):undefined
  return <div className="relative"><div className="overflow-auto rounded-2xl border bg-surface shadow-sm"><div className="min-w-max"><div className="sticky top-0 z-20 grid bg-surface" style={{gridTemplateColumns:`18rem repeat(${days.length},2.75rem)`}}><div className="sticky left-0 z-30 border-b border-r bg-surface p-3" />{days.map((day)=>{const holiday=holidayByDate.get(day);const date=new Date(`${day}T00:00:00Z`);return <button className={`border-b border-r p-1.5 text-center text-[11px] font-semibold hover:bg-accent ${holiday?'bg-accent text-accent-foreground':''}`} key={day} onClick={()=>setSelection({type:'day',date:day})} title={holiday?.display_name??holiday?.provider_name}><span className="block text-[9px] uppercase text-muted-foreground">{new Intl.DateTimeFormat(undefined,{weekday:'short',timeZone:'UTC'}).format(date)}</span>{Number(day.slice(-2))}</button>})}</div>{employees.map((employee)=><div className="grid min-h-14" key={employee.id} style={{gridTemplateColumns:`18rem repeat(${days.length},2.75rem)`}}><Link className="sticky left-0 z-10 flex items-center gap-3 border-b border-r bg-surface p-2.5 text-sm font-semibold hover:text-primary" href={`/employees/${employee.id}`}><span className="grid size-8 shrink-0 place-items-center rounded-full bg-accent text-[10px] font-bold text-accent-foreground">{employee.first_name[0]}{employee.birth_name[0]}</span><span className="min-w-0 truncate">{employee.first_name} {employee.birth_name}<span className="block text-[11px] font-normal text-muted-foreground">{(employee.averageMinutesPerWeek/60).toLocaleString(undefined,{maximumFractionDigits:2})} {labels.hoursPerWeek}</span></span></Link>{days.map((day)=>{const items=grouped.get(employee.id)?.get(day)??[];const dayReminders=remindersByEmployee.get(employee.id)?.get(day)??[];const work=employee.workDays[day];const holiday=holidayByDate.get(day);return <button className={`relative flex min-h-14 flex-col items-center justify-center gap-1 border-b border-r p-1 hover:bg-accent/70 ${holiday?'bg-accent/35':''}`} key={day} onClick={()=>setSelection({type:'employee',date:day,employee})} title={work?.isWorkingDay?`${labels.workHours} ${work.scheduledMinutes/60}h`:labels.nonWorking}>{work&&!work.isWorkingDay?<span className="h-1.5 w-full rounded-full bg-muted-foreground/45"/>:null}<span className="flex flex-wrap justify-center gap-0.5">{items.map((event)=><span aria-label={labels.events[event.eventType]} className={`size-2 rounded-full ${event.severity==='ATTENTION'?'bg-warning':'bg-primary'}`} key={event.id}/>)}</span>{dayReminders.length?<Bell className="text-accent-foreground" size={11}/>:null}</button>})}</div>)}</div></div>{employees.length===0?<p className="p-8 text-center text-sm text-muted-foreground">{labels.noEvents}</p>:null}
  {selection?<aside className="fixed inset-y-0 right-0 z-50 w-[min(28rem,calc(100vw-2rem))] overflow-y-auto border-l bg-surface p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">{selection.type==='day'?labels.dayDetails:labels.employeeDayDetails}</p><h2 className="mt-2 text-xl font-semibold">{selection.type==='employee'?`${selection.employee.first_name} ${selection.employee.birth_name} · `:''}{selection.date}</h2></div><button aria-label={labels.close} className="grid size-9 place-items-center rounded-lg hover:bg-muted" onClick={()=>setSelection(null)} type="button"><X size={18}/></button></div>{selectedHoliday?<div className="mt-5 rounded-xl bg-accent p-4"><p className="text-xs font-semibold uppercase tracking-wide">{labels.holiday}</p><p className="mt-1 font-semibold">{selectedHoliday.display_name??selectedHoliday.provider_name}</p></div>:null}{selection.type==='employee'?<><div className="mt-5 rounded-xl border p-4"><div className="flex items-center gap-2 font-semibold"><Clock3 className="text-primary" size={17}/>{selectedWorkDay?.isWorkingDay?labels.workHours:labels.nonWorking}</div>{selectedWorkDay?.isWorkingDay?<p className="mt-2 text-sm text-muted-foreground">{selectedWorkDay.startsAt} — {selectedWorkDay.endsAt} · {selectedWorkDay.scheduledMinutes/60}h</p>:null}</div><div className="mt-5 space-y-2">{selectedEmployeeEvents.map((event)=><Link className="block rounded-xl bg-muted p-3 text-sm font-semibold hover:text-primary" href={event.sourceHref} key={event.id}>{labels.events[event.eventType]}</Link>)}{selectedEmployeeReminders.map((reminder)=><div className="flex items-center gap-2 rounded-xl bg-muted p-3 text-sm" key={reminder.id}><Bell size={15}/>{reminder.title}</div>)}</div><button className="mt-6 w-full rounded-xl border border-dashed p-4 text-sm font-semibold text-muted-foreground" disabled type="button">{labels.actionsLater}</button></>:<div className="mt-5 space-y-2">{generalReminders.filter((reminder)=>reminder.date===selection.date).map((reminder)=><div className="flex items-center gap-2 rounded-xl bg-muted p-3 text-sm" key={reminder.id}><Bell size={15}/>{labels.reminder}: {reminder.title}</div>)}{events.filter((event)=>event.eventDate===selection.date).map((event)=><Link className="flex items-center gap-2 rounded-xl bg-muted p-3 text-sm" href={event.sourceHref} key={event.id}><CalendarDays size={15}/>{labels.events[event.eventType]}</Link>)}</div>}</aside>:null}</div>
}
