'use client'

import { useState } from 'react'
import { Dialog } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Surface } from '@/components/ui/surface'
import { TextInput } from '@/components/ui/text-input'
import { DropdownSelect } from '@/components/ui/dropdown-select'
import type { DocumentStudioTypeRow } from '@/lib/document-studio/repository'

type Labels = { readonly title: string; readonly new: string; readonly code: string; readonly name: string; readonly retention: string; readonly permanent: string; readonly years: string; readonly empty: string; readonly save: string; readonly cancel: string; readonly failed: string }

export function DocumentTypeManager({ initial, labels }: { initial: readonly DocumentStudioTypeRow[]; labels: Labels }) {
  const [items, setItems] = useState([...initial]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<DocumentStudioTypeRow | null>(null); const [error, setError] = useState<string | null>(null)
  function begin(item?: DocumentStudioTypeRow) { setEditing(item ?? null); setError(null); setOpen(true) }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const retentionKind = String(form.get('retentionKind') ?? 'PERMANENT'); const body = { code: String(form.get('code') ?? ''), name: { nl: String(form.get('nameNl') ?? ''), en: String(form.get('nameEn') ?? '') }, description: { nl: '', en: '' }, retentionKind, retentionYears: retentionKind === 'YEARS' ? Number(form.get('retentionYears') ?? 0) : null, isActive: true }; const response = await fetch(editing ? `/api/document-studio/document-types/${editing.id}` : '/api/document-studio/document-types', { method: editing ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) { setError(labels.failed); return } const result = await response.json() as { data: DocumentStudioTypeRow }; setItems((current) => editing ? current.map((item) => item.id === editing.id ? result.data : item) : [result.data, ...current]); setOpen(false) }
  return <><Surface className="overflow-x-auto"><div className="flex items-center justify-between gap-3 border-b border-border p-4"><h2 className="font-semibold">{labels.title}</h2><Button onClick={() => begin()} size="sm" type="button">{labels.new}</Button></div>{items.length ? <table className="min-w-[40rem] w-full text-left text-sm"><thead className="border-b border-border bg-surface-subtle text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">{labels.code}</th><th className="px-4 py-3">{labels.name}</th><th className="px-4 py-3">{labels.retention}</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-border">{items.map((item) => <tr key={item.id}><td className="px-4 py-3">{item.code}</td><td className="px-4 py-3">{item.name.nl}</td><td className="px-4 py-3">{item.retention_kind === 'YEARS' ? `${item.retention_years}` : labels.permanent}</td><td className="px-4 py-3 text-right"><Button onClick={() => begin(item)} size="sm" type="button" variant="ghost">{labels.name}</Button></td></tr>)}</tbody></table> : <p className="p-6 text-sm text-muted-foreground">{labels.empty}</p>}</Surface><Dialog closeLabel={labels.cancel} onOpenChange={setOpen} open={open} title={editing ? labels.name : labels.new}><form className="space-y-4" onSubmit={submit}>{error ? <p className="text-sm text-destructive" role="alert">{error}</p> : null}<label className="block space-y-1 text-sm font-medium">{labels.code}<TextInput defaultValue={editing?.code} name="code" required /></label><label className="block space-y-1 text-sm font-medium">{labels.name} NL<TextInput defaultValue={editing?.name.nl} name="nameNl" required /></label><label className="block space-y-1 text-sm font-medium">{labels.name} EN<TextInput defaultValue={editing?.name.en} name="nameEn" required /></label><label className="block space-y-1 text-sm font-medium">{labels.retention}<DropdownSelect defaultValue={editing?.retention_kind ?? 'PERMANENT'} name="retentionKind"><option value="PERMANENT">{labels.permanent}</option><option value="YEARS">{labels.years}</option></DropdownSelect></label><label className="block space-y-1 text-sm font-medium">{labels.years}<TextInput defaultValue={editing?.retention_years ?? ''} min="1" name="retentionYears" type="number" /></label><Button type="submit">{labels.save}</Button></form></Dialog></>
}
