import { notFound, redirect } from 'next/navigation'
import { LeaveTypeEditor } from '@/components/leave/leave-type-editor'
import { AdminSettingsPageHeader } from '@/components/settings/admin-settings-page-header'
import { AuthorizationError, requirePermission } from '@/lib/auth/permissions'
import { getTranslator } from '@/lib/i18n/server'
import { listLeaveCatalog } from '@/lib/leave/leave-service'

export default async function LeaveTypePage({ params }: { params: Promise<{ leaveTypeId: string }> }) {
  try { await requirePermission('leave:write') } catch (error) { if (error instanceof AuthorizationError) redirect('/geen-toegang'); throw error }
  const [{ leaveTypeId }, catalog, labels] = await Promise.all([params, listLeaveCatalog(), getTranslator('leave')])
  const leaveType = catalog.leaveTypes.find((item) => item.id === leaveTypeId)
  if (!leaveType) notFound()
  const year = new Date().getFullYear()
  return <div className="mx-auto w-full max-w-6xl px-5 py-8 lg:px-10"><AdminSettingsPageHeader backLabel={labels('page.back')} backHref="/settings/leave-accrual" eyebrow={labels('page.title')} title={labels('type.editTitle', { name: leaveType.name, year })} /><LeaveTypeEditor catalog={catalog} existing={leaveType} mode="leave" labels={typeLabels(labels)} /></div>
}

function typeLabels(t: Awaited<ReturnType<typeof getTranslator>>) {
  const ruleLabels = { title: t('type.ruleTitle'), description: t('rule.chainDescription'), empty: t('type.ruleEmpty'), add: t('type.addRule'), version: t('rule.version'), current: t('rule.current'), ended: t('rule.validUntil'), successor: t('rule.successor'), select: t('rule.successor'), profile: t('rule.profile'), contractHours: t('type.contractHours'), workedHours: t('type.workedHours'), ageSeniority: t('type.ageSeniority'), payrollPeriod: t('type.payrollPeriod'), yearly: t('type.yearly'), upfront: t('type.upfront'), arrears: t('type.arrears'), amount: t('rule.amount'), rate: t('rule.rate'), validFrom: t('rule.successorStart'), validUntil: t('rule.validUntil'), noValue: t('rule.noValue') }
  const exceptionLabels = { title: t('exception.title'), description: t('exception.description'), empty: t('exception.empty'), add: t('exception.add'), name: t('exception.name'), summary: t('exception.summary'), validFrom: t('exception.validFrom'), validUntil: t('exception.validUntil'), noValue: t('exception.noValue'), noAccrual: t('exception.noAccrual'), customAmount: t('exception.customAmount'), amount: t('exception.amount'), expiry: t('exception.expiry'), months: t('exception.months'), reason: t('exception.reason'), selectionMode: t('exception.selectionMode'), onePerson: t('exception.onePerson'), multiplePeople: t('exception.multiplePeople'), selectPerson: t('exception.selectPerson'), selectPeople: t('exception.selectPeople'), search: t('exception.search'), selectVisible: t('exception.selectVisible'), selected: t('exception.selected'), save: t('exception.save'), cancel: t('exception.cancel'), saving: t('exception.saving'), saved: t('exception.saved'), failed: t('exception.failed'), previous: t('exception.previous'), next: t('exception.next'), page: t('exception.page') }
  const bonusLabels = { title: t('bonus.title'), description: t('bonus.description'), empty: t('bonus.empty'), add: t('bonus.add'), tileAge: t('bonus.tileAge'), tileSeniority: t('bonus.tileSeniority'), name: t('bonus.name'), profile: t('bonus.profile'), trigger: t('bonus.trigger'), age: t('bonus.age'), seniority: t('bonus.seniority'), timing: t('bonus.timing'), startOfYear: t('bonus.startOfYear'), onTriggerDate: t('bonus.onTriggerDate'), proRate: t('bonus.proRate'), proRateHelp: t('bonus.proRateHelp'), tiers: t('bonus.tiers'), thresholdYears: t('bonus.thresholdYears'), bonusAmount: t('bonus.bonusAmount'), addTier: t('bonus.addTier'), removeTier: t('bonus.removeTier'), summary: t('bonus.summary'), save: t('bonus.save'), cancel: t('bonus.cancel'), saving: t('bonus.saving'), saved: t('bonus.saved'), failed: t('bonus.failed'), noTiers: t('bonus.noTiers'), current: t('bonus.current'), inactive: t('bonus.inactive'), fullTime: t('bonus.fullTime'), selectTrigger: t('bonus.selectTrigger') }
  return {
    save: t('page.save'), archive: t('page.archive'), saving: t('page.saving'), saved: t('page.saved'), failed: t('page.failed'),
    tabs: { base: t('type.baseTab'), limits: t('type.limitsTab'), advanced: t('type.advancedTab') }, name: t('type.name'), color: t('type.color'),
    colorOptions: { blue: t('type.colorBlue'), teal: t('type.colorTeal'), green: t('type.colorGreen'), orange: t('type.colorOrange'), red: t('type.colorRed'), primary: t('type.colorPrimary'), success: t('type.colorSuccess'), warning: t('type.colorWarning'), destructive: t('type.colorDestructive'), accent: t('type.colorAccent'), muted: t('type.colorMuted'), sidebar: t('type.colorSidebar') },
    scope: t('type.scope'), scopeStatutory: t('type.scopeStatutory'), scopeNonStatutory: t('type.scopeNonStatutory'), scopeAdv: t('type.scopeAdv'), scopeOther: t('type.scopeOther'), category: t('type.category'), regularWork: t('type.regularWork'), overtime: t('type.overtime'), informational: t('type.informational'), activeLabel: t('type.activeLabel'), selfService: t('type.selfService'), entitlement: t('type.entitlement'), accrual: t('type.accrual'), unlimited: t('type.unlimited'), annualCap: t('type.annualCap'), weeklyFactorCap: t('type.weeklyFactorCap'), annualCapValue: t('type.annualCapValue'), weeklyFactor: t('type.weeklyFactor'), notApplicable: t('type.notApplicable'),
    ruleList: ruleLabels, bonusPanel: bonusLabels, exceptionPanel: exceptionLabels, leaveSettings: { title: t('type.leaveSettingsTitle'), allowLimitOverrun: t('type.allowLimitOverrun'), pinInCalendar: t('type.pinInCalendar'), requiresManagerApproval: t('type.requiresManagerApproval'), notifyManagerOnRequest: t('type.notifyManagerOnRequest'), requiresManagerApprovalOnCancellation: t('type.requiresManagerApprovalOnCancellation') }, advancedPlaceholder: t('type.advancedPlaceholder'),
  }
}
